//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NastiAplicacion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICULO()
        {
            this.ARTICULOCOMPONENTE = new HashSet<ARTICULOCOMPONENTE>();
            this.ARTICULOCOMPONENTE1 = new HashSet<ARTICULOCOMPONENTE>();
            this.ARTICULOIMPUESTO = new HashSet<ARTICULOIMPUESTO>();
            this.BODEGASTOCK = new HashSet<BODEGASTOCK>();
            this.DETALLECOMPROBANTE = new HashSet<DETALLECOMPROBANTE>();
            this.DETALLELISTADEPRECIO = new HashSet<DETALLELISTADEPRECIO>();
        }
    
        public long CODIGOEMPRESA { get; set; }
        public long CODIGOARTICULO { get; set; }
        public string CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal COSTO { get; set; }
        public decimal PRECIOVENTA { get; set; }
        public decimal CANTIDAD { get; set; }
        public long CODIGOIMPUESTO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<long> CODIGOUNIDAD { get; set; }
        public string SECCION { get; set; }
        public Nullable<decimal> INGRESOS { get; set; }
        public Nullable<decimal> EGRESOS { get; set; }
        public Nullable<decimal> SALDOINICIAL { get; set; }
        public string DESCRIPCIONCORTA { get; set; }
        public Nullable<decimal> STOCKMINIMO { get; set; }
        public Nullable<decimal> STOCKMAXIMO { get; set; }
        public string ENPANTALLA { get; set; }
        public byte[] GRAFICO { get; set; }
        public long CODIGOTIPOARTICULO { get; set; }
        public string SOLOCOMPRAS { get; set; }
        public string VENTAS { get; set; }
        public string INVENTARIO { get; set; }
        public System.DateTime FECHACREACION { get; set; }
        public System.DateTime FECHAMODIFICACION { get; set; }
        public string PRECIOVARIABLE { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual IMPUESTO IMPUESTO { get; set; }
        public virtual TIPOARTICULO TIPOARTICULO { get; set; }
        public virtual UNIDAD UNIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULOCOMPONENTE> ARTICULOCOMPONENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULOCOMPONENTE> ARTICULOCOMPONENTE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULOIMPUESTO> ARTICULOIMPUESTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BODEGASTOCK> BODEGASTOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLECOMPROBANTE> DETALLECOMPROBANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLELISTADEPRECIO> DETALLELISTADEPRECIO { get; set; }
    }
}
