//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NastiAplicacion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BODEGA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BODEGA()
        {
            this.BODEGASTOCK = new HashSet<BODEGASTOCK>();
            this.COMPROBANTE = new HashSet<COMPROBANTE>();
            this.DETALLECOMPROBANTE = new HashSet<DETALLECOMPROBANTE>();
        }
    
        public long CODIGOBODEGA { get; set; }
        public long CODIGOEMPRESA { get; set; }
        public string NOMBRE { get; set; }
        public long CODIGOESTABLECIMIENTO { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ESTABLECIMIENTO ESTABLECIMIENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BODEGASTOCK> BODEGASTOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPROBANTE> COMPROBANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLECOMPROBANTE> DETALLECOMPROBANTE { get; set; }
    }
}
