//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NastiAplicacion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPROBANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPROBANTE()
        {
            this.COMPROBANTEFORMAPAGO = new HashSet<COMPROBANTEFORMAPAGO>();
            this.DETALLECOMPROBANTE = new HashSet<DETALLECOMPROBANTE>();
            this.IMPUESTOCOMPROBANTE = new HashSet<IMPUESTOCOMPROBANTE>();
        }
    
        public long CODIGOCOMPROBANTE { get; set; }
        public long CODIGOEMPRESA { get; set; }
        public long CODIGOTIPOCOMPROBANTE { get; set; }
        public long CODIGOPUNTOEMISION { get; set; }
        public long CODIGOESTABLECIMIENTO { get; set; }
        public long NUMEROCOMPROBANTE { get; set; }
        public System.DateTime FECHAEMISION { get; set; }
        public Nullable<long> CODIGOSOCIONEGOCIO { get; set; }
        public decimal TOTALSINIMPUESTO { get; set; }
        public decimal TOTAL { get; set; }
        public Nullable<long> CODIGOLISTADEPRECIO { get; set; }
        public Nullable<decimal> DESCUENTOADICIONAL { get; set; }
        public int ESTADO { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<int> PAGADO { get; set; }
        public string INFORMACIONADICIONAL { get; set; }
        public Nullable<long> CODIGOVENDEDOR { get; set; }
        public long CODIGOESTADOCOMPROBANTE { get; set; }
        public string CLAVEDEACCESO { get; set; }
        public string AUTORIZACION { get; set; }
        public byte[] ARCHIVOAUTORIZADO { get; set; }
        public Nullable<decimal> VALORRECIBIDO { get; set; }
        public Nullable<decimal> CAMBIO { get; set; }
        public Nullable<long> CODIGOBODEGA { get; set; }
        public string NOVEDAD { get; set; }
        public Nullable<System.DateTime> FECHAAUTORIZACION { get; set; }
        public Nullable<long> CODIGOEJERCICIOFISCAL { get; set; }
    
        public virtual BODEGA BODEGA { get; set; }
        public virtual EJERCICIOFISCAL EJERCICIOFISCAL { get; set; }
        public virtual ESTADOCOMPROBANTE ESTADOCOMPROBANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPROBANTEFORMAPAGO> COMPROBANTEFORMAPAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLECOMPROBANTE> DETALLECOMPROBANTE { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ESTABLECIMIENTO ESTABLECIMIENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPUESTOCOMPROBANTE> IMPUESTOCOMPROBANTE { get; set; }
        public virtual PUNTOEMISION PUNTOEMISION { get; set; }
        public virtual SOCIONEGOCIO SOCIONEGOCIO { get; set; }
        public virtual TIPOCOMPROBANTE TIPOCOMPROBANTE { get; set; }
        public virtual SOCIONEGOCIO SOCIONEGOCIO1 { get; set; }
    }
}
