//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NastiAplicacion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPRESA()
        {
            this.ARTICULO = new HashSet<ARTICULO>();
            this.BODEGA = new HashSet<BODEGA>();
            this.CLIENTE = new HashSet<CLIENTE>();
            this.COMPROBANTE = new HashSet<COMPROBANTE>();
            this.EJERCICIOFISCAL = new HashSet<EJERCICIOFISCAL>();
            this.UNIDAD = new HashSet<UNIDAD>();
            this.ESTABLECIMIENTO1 = new HashSet<ESTABLECIMIENTO>();
            this.FORMAPAGO = new HashSet<FORMAPAGO>();
            this.IMPUESTO = new HashSet<IMPUESTO>();
            this.LISTADEPRECIO = new HashSet<LISTADEPRECIO>();
            this.PARAMETRO = new HashSet<PARAMETRO>();
            this.PROVEEDOR = new HashSet<PROVEEDOR>();
            this.SOCIONEGOCIO = new HashSet<SOCIONEGOCIO>();
            this.USUARIOEMPRESA = new HashSet<USUARIOEMPRESA>();
            this.VENDEDOR = new HashSet<VENDEDOR>();
        }
    
        public long CODIGOEMPRESA { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION1 { get; set; }
        public string TELEFONO1 { get; set; }
        public string DIRECCION2 { get; set; }
        public string TELEFONO2 { get; set; }
        public string RUC { get; set; }
        public Nullable<int> DURACIONDIA { get; set; }
        public string LUGAR { get; set; }
        public string FAC { get; set; }
        public string MASCTA { get; set; }
        public string CIUDAD { get; set; }
        public Nullable<System.DateTime> INICIOPERIODO { get; set; }
        public Nullable<System.DateTime> FINPERIODO { get; set; }
        public string PERIODO { get; set; }
        public string CODIGOCUENTA { get; set; }
        public string CUENTAINGRESO { get; set; }
        public string CUENTAGASTO { get; set; }
        public Nullable<System.DateTime> FECHACIERRE { get; set; }
        public string CODIGOUSUARIO { get; set; }
        public Nullable<System.DateTime> FECHAACTUALIZACION { get; set; }
        public string EMPRESAACT { get; set; }
        public string EMPRESACON { get; set; }
        public string CUENTAACTIVO { get; set; }
        public string CUENTAPASIVO { get; set; }
        public string CUENTAPATRIMONIO { get; set; }
        public string CODIGOMONEDA { get; set; }
        public Nullable<System.DateTime> FECHACAL { get; set; }
        public string TIPO { get; set; }
        public string CORREOELECTRONICO { get; set; }
        public string IDENTIFICACIONREPRESENTANTE { get; set; }
        public string RUCCONTADOR { get; set; }
        public string TIPOIDENTIFICACIONREPRESENTANTE { get; set; }
        public string AUTORIZACION { get; set; }
        public string CUENTAGASTO2 { get; set; }
        public string CUENTAORDEN { get; set; }
        public string CUENTAORDEN2 { get; set; }
        public string TIPOCUENTAS { get; set; }
        public string CODIGOENTIDAD { get; set; }
        public string NUMESTABLECIMIENTOS { get; set; }
        public byte[] FIRMAELECTRONICA { get; set; }
        public string ESTABLECIMIENTO { get; set; }
        public string CLAVEFIRMA { get; set; }
        public byte[] LOGO { get; set; }
        public string NOMBRECOMERCIAL { get; set; }
        public Nullable<long> CODIGOTIPOAMBIENTE { get; set; }
        public string CONTRIBUYENTEESPECIAL { get; set; }
        public string LLEVACONTABILIDAD { get; set; }
        public string NUMERORESOLUCION { get; set; }
        public Nullable<System.DateTime> FECHACADUCIDAD { get; set; }
        public Nullable<int> CODIGOPROVEEDORCERTIFICADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO> ARTICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BODEGA> BODEGA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPROBANTE> COMPROBANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EJERCICIOFISCAL> EJERCICIOFISCAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNIDAD> UNIDAD { get; set; }
        public virtual PROVEEDORCERTIFICADO PROVEEDORCERTIFICADO { get; set; }
        public virtual TIPOAMBIENTE TIPOAMBIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTABLECIMIENTO> ESTABLECIMIENTO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORMAPAGO> FORMAPAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPUESTO> IMPUESTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTADEPRECIO> LISTADEPRECIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARAMETRO> PARAMETRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROVEEDOR> PROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOCIONEGOCIO> SOCIONEGOCIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOEMPRESA> USUARIOEMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENDEDOR> VENDEDOR { get; set; }
    }
}
