//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NastiAplicacion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPUESTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMPUESTO()
        {
            this.ARTICULO = new HashSet<ARTICULO>();
            this.ARTICULOIMPUESTO = new HashSet<ARTICULOIMPUESTO>();
            this.DETALLECOMPROBANTE = new HashSet<DETALLECOMPROBANTE>();
            this.IMPUESTOCOMPROBANTE = new HashSet<IMPUESTOCOMPROBANTE>();
        }
    
        public long CODIGOIMPUESTO { get; set; }
        public int CODIGOTIPOIMPUESTO { get; set; }
        public decimal PORCENTAJE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<System.DateTime> FECHADESDE { get; set; }
        public Nullable<System.DateTime> FECHAHASTA { get; set; }
        public string CODIGOSRI { get; set; }
        public string DESGLOSADO { get; set; }
        public Nullable<long> CODIGOEMPRESA { get; set; }
        public string ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULO> ARTICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICULOIMPUESTO> ARTICULOIMPUESTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLECOMPROBANTE> DETALLECOMPROBANTE { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual TIPOIMPUESTO TIPOIMPUESTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPUESTOCOMPROBANTE> IMPUESTOCOMPROBANTE { get; set; }
    }
}
