//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NastiAplicacion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTADEPRECIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LISTADEPRECIO()
        {
            this.DETALLELISTADEPRECIO = new HashSet<DETALLELISTADEPRECIO>();
        }
    
        public long CODIGOLISTADEPRECIO { get; set; }
        public string DESCRIPCION { get; set; }
        public long CODIGOEMPRESA { get; set; }
        public Nullable<long> CODIGOSOCIONEGOCIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLELISTADEPRECIO> DETALLELISTADEPRECIO { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual SOCIONEGOCIO SOCIONEGOCIO { get; set; }
    }
}
