//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NastiAplicacion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUNTOEMISIONAUTORIZACION
    {
        public long CODIGOPUNTOEMISIONAUTORIZACION { get; set; }
        public long CODIGOPUNTOEMISIONDOCUMENTO { get; set; }
        public System.DateTime FECHAINICIAL { get; set; }
        public System.DateTime FECHAFINAL { get; set; }
        public string AUTORIZACION { get; set; }
    
        public virtual PUNTOEMISIONDOCUMENTO PUNTOEMISIONDOCUMENTO { get; set; }
    }
}
