//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NastiAplicacion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCIONEGOCIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOCIONEGOCIO()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
            this.COMPROBANTE = new HashSet<COMPROBANTE>();
            this.COMPROBANTE1 = new HashSet<COMPROBANTE>();
            this.LISTADEPRECIO = new HashSet<LISTADEPRECIO>();
        }
    
        public long CODIGOSOCIONEGOCIO { get; set; }
        public Nullable<long> CODIGOEMPRESA { get; set; }
        public string RAZONSOCIAL { get; set; }
        public string NUMERODOCUMENTO { get; set; }
        public string DIRECCION { get; set; }
        public string DIRECCION2 { get; set; }
        public string TELEFONO { get; set; }
        public string TELEFONO2 { get; set; }
        public string FAX { get; set; }
        public string CONTACTO { get; set; }
        public string ESTATUS { get; set; }
        public string CODIGOUSUARIO { get; set; }
        public Nullable<System.DateTime> FECHAACTUALIZACION { get; set; }
        public string CIUDAD { get; set; }
        public string EMAIL { get; set; }
        public string COMENTARIO { get; set; }
        public string CODIGOPROVINCIA { get; set; }
        public string ESTADOCIVIL { get; set; }
        public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
        public string NOMBRECOMERCIAL { get; set; }
        public Nullable<decimal> SUELDO { get; set; }
        public long CODIGOTIPOIDENTIFICACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPROBANTE> COMPROBANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPROBANTE> COMPROBANTE1 { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTADEPRECIO> LISTADEPRECIO { get; set; }
        public virtual TIPOIDENTIFICACION TIPOIDENTIFICACION { get; set; }
    }
}
