//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NastiAplicacion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.USUARIOEMPRESA = new HashSet<USUARIOEMPRESA>();
        }
    
        public long CODIGOUSUARIO { get; set; }
        public string TIPOUSUARIO { get; set; }
        public string CLAVE { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<System.DateTime> FECHAINGRESO { get; set; }
        public Nullable<System.DateTime> FECHAEXPIDE { get; set; }
        public string TIPOACCESO { get; set; }
        public Nullable<System.DateTime> FECHAACTUALIZACION { get; set; }
        public string NOMBRECOMPLETO { get; set; }
        public string conectado { get; set; }
        public string EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOEMPRESA> USUARIOEMPRESA { get; set; }
    }
}
