//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NastiAplicacion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOEMPRESA
    {
        public long CODIGOUSUARIOEMPRESA { get; set; }
        public long CODIGOUSUARIO { get; set; }
        public long CODIGOEMPRESA { get; set; }
        public Nullable<long> CODIGOESTADO { get; set; }
        public Nullable<long> CODIGOESTABLECIMIENTO { get; set; }
        public string CENTROCOSTO { get; set; }
        public string TIPO_CO { get; set; }
        public string TIPO_FC { get; set; }
        public string TIPO_FV { get; set; }
        public string TIPO_PP { get; set; }
        public string TIPO_CC { get; set; }
        public string SUPERVISOR { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
