//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NastiAplicacion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDEDOR
    {
        public long CODIGOVENDEDOR { get; set; }
        public Nullable<long> CODIGOEMPRESA { get; set; }
        public string SIGLA { get; set; }
        public Nullable<long> CODIGOSOCIONEGOCIO { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
