//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nasti.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULOCOMPONENTE
    {
        public long CODIGOARTICULOCOMPONENTE { get; set; }
        public Nullable<long> CODIGOARTICULO { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<long> CODIGOUNIDAD { get; set; }
        public string ESTADO { get; set; }
        public Nullable<long> CODIGOARTICULOCOMP { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
        public virtual ARTICULO ARTICULO1 { get; set; }
        public virtual UNIDAD UNIDAD { get; set; }
    }
}
