//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nasti.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDICIONPAGO
    {
        public string CODIGOCONDICIONPAGO { get; set; }
        public string PRECIONORMAL { get; set; }
        public Nullable<int> DIASCREDITO { get; set; }
    }
}
