//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nasti.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLECOMPROBANTEADICIONAL
    {
        public long CODIGODETALLECOMPROBANTEADICIONAL { get; set; }
        public long CODIGOCOMPROBANTE { get; set; }
        public string TITULO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual COMPROBANTE COMPROBANTE { get; set; }
    }
}
