//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nasti.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLECOMPROBANTE
    {
        public long CODIGODETALLECOMPROBANTE { get; set; }
        public long CODIGOCOMPROBANTE { get; set; }
        public int NUMEROCOMPROBANTE { get; set; }
        public int NUMEROLINEA { get; set; }
        public long CODIGOARTICULO { get; set; }
        public string DESCRIPCIONARTICULO { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal PVP { get; set; }
        public Nullable<decimal> DESCUENTO { get; set; }
        public Nullable<decimal> PORCENTAJEDESCUENTO { get; set; }
        public int ESTADO { get; set; }
        public long CODIGOESTABLECIMIENTO { get; set; }
        public long CODIGOPUNTOEMISION { get; set; }
        public long CODIGOTIPODOCUMENTO { get; set; }
        public long CODIGOIMPUESTO { get; set; }
        public decimal PORCENTAJEIMPUESTO { get; set; }
        public Nullable<decimal> VALORIMPUESTO { get; set; }
        public Nullable<decimal> BASEIMPONIBLE { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public long CODIGOBODEGA { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
        public virtual BODEGA BODEGA { get; set; }
        public virtual COMPROBANTE COMPROBANTE { get; set; }
        public virtual IMPUESTO IMPUESTO { get; set; }
    }
}
