//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nasti.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELEMENTO
    {
        public long CODIGOELEMENTO { get; set; }
        public string NOMBRE { get; set; }
        public string GRAFICO { get; set; }
        public Nullable<int> ORDEN { get; set; }
        public Nullable<long> CODIGOTIPOELEMENTO { get; set; }
        public string TIPO { get; set; }
        public string ACCION { get; set; }
        public Nullable<long> codigoelemento_ { get; set; }
    
        public virtual TIPOELEMENTO TIPOELEMENTO { get; set; }
    }
}
