
-- --------------------------------------------------
-- Entity Designer DDL Script for SQL Server 2005, 2008, 2012 and Azure
-- --------------------------------------------------
-- Date Created: 01/24/2020 12:00:39
-- Generated from EDMX file: C:\Users\robay\OneDrive\Kippa\Fuentes\NastiAplicacion\NastiAplicacion\Data\ModeloNasti.edmx
-- --------------------------------------------------

SET QUOTED_IDENTIFIER OFF;
GO
USE [kippa];
GO
IF SCHEMA_ID(N'dbo') IS NULL EXECUTE(N'CREATE SCHEMA [dbo]');
GO

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[FK_ARTICULO_EMPRESA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ARTICULO] DROP CONSTRAINT [FK_ARTICULO_EMPRESA];
GO
IF OBJECT_ID(N'[dbo].[FK_ARTICULO_IMPUESTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ARTICULO] DROP CONSTRAINT [FK_ARTICULO_IMPUESTO];
GO
IF OBJECT_ID(N'[dbo].[FK_ARTICULO_TIPOARTICULO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ARTICULO] DROP CONSTRAINT [FK_ARTICULO_TIPOARTICULO];
GO
IF OBJECT_ID(N'[dbo].[FK_ARTICULO_UNIDAD]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ARTICULO] DROP CONSTRAINT [FK_ARTICULO_UNIDAD];
GO
IF OBJECT_ID(N'[dbo].[FK_ARTICULOCOMPONENTE_ARTICULO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ARTICULOCOMPONENTE] DROP CONSTRAINT [FK_ARTICULOCOMPONENTE_ARTICULO];
GO
IF OBJECT_ID(N'[dbo].[FK_ARTICULOCOMPONENTE_ARTICULOCOMP]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ARTICULOCOMPONENTE] DROP CONSTRAINT [FK_ARTICULOCOMPONENTE_ARTICULOCOMP];
GO
IF OBJECT_ID(N'[dbo].[FK_ARTICULOCOMPONENTE_UNIDAD]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ARTICULOCOMPONENTE] DROP CONSTRAINT [FK_ARTICULOCOMPONENTE_UNIDAD];
GO
IF OBJECT_ID(N'[dbo].[FK_ARTICULOIMPUESTO_ARTICULO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ARTICULOIMPUESTO] DROP CONSTRAINT [FK_ARTICULOIMPUESTO_ARTICULO];
GO
IF OBJECT_ID(N'[dbo].[FK_ARTICULOIMPUESTO_IMPUESTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ARTICULOIMPUESTO] DROP CONSTRAINT [FK_ARTICULOIMPUESTO_IMPUESTO];
GO
IF OBJECT_ID(N'[dbo].[FK_BODEGA_EMPRESA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[BODEGA] DROP CONSTRAINT [FK_BODEGA_EMPRESA];
GO
IF OBJECT_ID(N'[dbo].[FK_BODEGA_ESTABLECIMIENTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[BODEGA] DROP CONSTRAINT [FK_BODEGA_ESTABLECIMIENTO];
GO
IF OBJECT_ID(N'[dbo].[FK_BODEGASTOCK_ARTICULO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[BODEGASTOCK] DROP CONSTRAINT [FK_BODEGASTOCK_ARTICULO];
GO
IF OBJECT_ID(N'[dbo].[FK_BODEGASTOCK_BODEGA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[BODEGASTOCK] DROP CONSTRAINT [FK_BODEGASTOCK_BODEGA];
GO
IF OBJECT_ID(N'[dbo].[FK_CLIENTE_SOCIONEGOCIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CLIENTE] DROP CONSTRAINT [FK_CLIENTE_SOCIONEGOCIO];
GO
IF OBJECT_ID(N'[dbo].[FK_CODIGOEMPRESA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[CLIENTE] DROP CONSTRAINT [FK_CODIGOEMPRESA];
GO
IF OBJECT_ID(N'[dbo].[FK_COMPROBANTE_BODEGA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[COMPROBANTE] DROP CONSTRAINT [FK_COMPROBANTE_BODEGA];
GO
IF OBJECT_ID(N'[dbo].[FK_COMPROBANTE_ESTADOCOMPROBANTE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[COMPROBANTE] DROP CONSTRAINT [FK_COMPROBANTE_ESTADOCOMPROBANTE];
GO
IF OBJECT_ID(N'[dbo].[FK_COMPROBANTEFORMAPAGO_COMPROBANTE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[COMPROBANTEFORMAPAGO] DROP CONSTRAINT [FK_COMPROBANTEFORMAPAGO_COMPROBANTE];
GO
IF OBJECT_ID(N'[dbo].[FK_COMPROBANTEFORMAPAGO_FORMAPAGO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[COMPROBANTEFORMAPAGO] DROP CONSTRAINT [FK_COMPROBANTEFORMAPAGO_FORMAPAGO];
GO
IF OBJECT_ID(N'[dbo].[FK_COMPROBANTEFORMAPAGO_UNIDADTIEMPO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[COMPROBANTEFORMAPAGO] DROP CONSTRAINT [FK_COMPROBANTEFORMAPAGO_UNIDADTIEMPO];
GO
IF OBJECT_ID(N'[dbo].[FK_DETALLECOMPROBANTE_ARTICULO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DETALLECOMPROBANTE] DROP CONSTRAINT [FK_DETALLECOMPROBANTE_ARTICULO];
GO
IF OBJECT_ID(N'[dbo].[FK_DETALLECOMPROBANTE_BODEGA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DETALLECOMPROBANTE] DROP CONSTRAINT [FK_DETALLECOMPROBANTE_BODEGA];
GO
IF OBJECT_ID(N'[dbo].[FK_DETALLECOMPROBANTE_COMPROBANTE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DETALLECOMPROBANTE] DROP CONSTRAINT [FK_DETALLECOMPROBANTE_COMPROBANTE];
GO
IF OBJECT_ID(N'[dbo].[FK_DETALLECOMPROBANTE_IMPUESTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DETALLECOMPROBANTE] DROP CONSTRAINT [FK_DETALLECOMPROBANTE_IMPUESTO];
GO
IF OBJECT_ID(N'[dbo].[FK_DETALLELISTADEPRECIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DETALLELISTADEPRECIO] DROP CONSTRAINT [FK_DETALLELISTADEPRECIO];
GO
IF OBJECT_ID(N'[dbo].[FK_DETALLELISTADEPRECIOARTICULO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DETALLELISTADEPRECIO] DROP CONSTRAINT [FK_DETALLELISTADEPRECIOARTICULO];
GO
IF OBJECT_ID(N'[dbo].[FK_EMPRESA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[UNIDAD] DROP CONSTRAINT [FK_EMPRESA];
GO
IF OBJECT_ID(N'[dbo].[FK_EMPRESA_PROVEEDORCERTIFICADO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[EMPRESA] DROP CONSTRAINT [FK_EMPRESA_PROVEEDORCERTIFICADO];
GO
IF OBJECT_ID(N'[dbo].[FK_EMPRESA_TIPOAMBIENTE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[EMPRESA] DROP CONSTRAINT [FK_EMPRESA_TIPOAMBIENTE];
GO
IF OBJECT_ID(N'[dbo].[FK_EMPRESACOMPROBANTE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[COMPROBANTE] DROP CONSTRAINT [FK_EMPRESACOMPROBANTE];
GO
IF OBJECT_ID(N'[dbo].[FK_ESTABLECIMIENTO_ToTable]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ESTABLECIMIENTO] DROP CONSTRAINT [FK_ESTABLECIMIENTO_ToTable];
GO
IF OBJECT_ID(N'[dbo].[FK_ESTABLECIMIENTOCOMPROBANTE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[COMPROBANTE] DROP CONSTRAINT [FK_ESTABLECIMIENTOCOMPROBANTE];
GO
IF OBJECT_ID(N'[dbo].[FK_ESTADOCOMPROBANTE_TIPOESTADO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ESTADOCOMPROBANTE] DROP CONSTRAINT [FK_ESTADOCOMPROBANTE_TIPOESTADO];
GO
IF OBJECT_ID(N'[dbo].[FK_FORMAPAGO_EMPRESA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[FORMAPAGO] DROP CONSTRAINT [FK_FORMAPAGO_EMPRESA];
GO
IF OBJECT_ID(N'[dbo].[FK_FORMAPAGO_TIPOFORMAPAGO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[FORMAPAGO] DROP CONSTRAINT [FK_FORMAPAGO_TIPOFORMAPAGO];
GO
IF OBJECT_ID(N'[dbo].[FK_IMPUESTO_EMPRESA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[IMPUESTO] DROP CONSTRAINT [FK_IMPUESTO_EMPRESA];
GO
IF OBJECT_ID(N'[dbo].[FK_IMPUESTO_TIPOIMPUESTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[IMPUESTO] DROP CONSTRAINT [FK_IMPUESTO_TIPOIMPUESTO];
GO
IF OBJECT_ID(N'[dbo].[FK_IMPUESTOCOMPROBANTE_COMPROBANTE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[IMPUESTOCOMPROBANTE] DROP CONSTRAINT [FK_IMPUESTOCOMPROBANTE_COMPROBANTE];
GO
IF OBJECT_ID(N'[dbo].[FK_IMPUESTOCOMPROBANTE_IMPUESTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[IMPUESTOCOMPROBANTE] DROP CONSTRAINT [FK_IMPUESTOCOMPROBANTE_IMPUESTO];
GO
IF OBJECT_ID(N'[dbo].[FK_LISTADEPRECIO_EMPRESA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[LISTADEPRECIO] DROP CONSTRAINT [FK_LISTADEPRECIO_EMPRESA];
GO
IF OBJECT_ID(N'[dbo].[FK_LISTADEPRECIO_SOCIONEGOCIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[LISTADEPRECIO] DROP CONSTRAINT [FK_LISTADEPRECIO_SOCIONEGOCIO];
GO
IF OBJECT_ID(N'[dbo].[FK_PARAMETROS_EMPRESA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PARAMETRO] DROP CONSTRAINT [FK_PARAMETROS_EMPRESA];
GO
IF OBJECT_ID(N'[dbo].[FK_PROVEEDOREMPRESA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PROVEEDOR] DROP CONSTRAINT [FK_PROVEEDOREMPRESA];
GO
IF OBJECT_ID(N'[dbo].[FK_PUNTOEMISIONAUTORIZACION_ToTable]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PUNTOEMISIONAUTORIZACION] DROP CONSTRAINT [FK_PUNTOEMISIONAUTORIZACION_ToTable];
GO
IF OBJECT_ID(N'[dbo].[FK_PUNTOEMISIONCOMPROBANTE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[COMPROBANTE] DROP CONSTRAINT [FK_PUNTOEMISIONCOMPROBANTE];
GO
IF OBJECT_ID(N'[dbo].[FK_PUNTOEMISIONDOCUMENTO_PUNTOEMISION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PUNTOEMISIONDOCUMENTO] DROP CONSTRAINT [FK_PUNTOEMISIONDOCUMENTO_PUNTOEMISION];
GO
IF OBJECT_ID(N'[dbo].[FK_PUNTOEMISIONDOCUMENTOTIPOCOMPROBANTE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PUNTOEMISIONDOCUMENTO] DROP CONSTRAINT [FK_PUNTOEMISIONDOCUMENTOTIPOCOMPROBANTE];
GO
IF OBJECT_ID(N'[dbo].[FK_PUNTOEMISIONESTABLECIMIENTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PUNTOEMISION] DROP CONSTRAINT [FK_PUNTOEMISIONESTABLECIMIENTO];
GO
IF OBJECT_ID(N'[dbo].[FK_SOCIONEGOCIO_TIPOIDENTIFICACION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[SOCIONEGOCIO] DROP CONSTRAINT [FK_SOCIONEGOCIO_TIPOIDENTIFICACION];
GO
IF OBJECT_ID(N'[dbo].[FK_SOCIONEGOCIOCOMPROBANTE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[COMPROBANTE] DROP CONSTRAINT [FK_SOCIONEGOCIOCOMPROBANTE];
GO
IF OBJECT_ID(N'[dbo].[FK_TIPO_ELEMENTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ELEMENTO] DROP CONSTRAINT [FK_TIPO_ELEMENTO];
GO
IF OBJECT_ID(N'[dbo].[FK_TIPOCOMPROBANTECOMPROBANTE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[COMPROBANTE] DROP CONSTRAINT [FK_TIPOCOMPROBANTECOMPROBANTE];
GO
IF OBJECT_ID(N'[dbo].[FK_USUARIOEMPRESA_EMPRESA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[USUARIOEMPRESA] DROP CONSTRAINT [FK_USUARIOEMPRESA_EMPRESA];
GO
IF OBJECT_ID(N'[dbo].[FK_USUARIOEMPRESA_USUARIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[USUARIOEMPRESA] DROP CONSTRAINT [FK_USUARIOEMPRESA_USUARIO];
GO
IF OBJECT_ID(N'[dbo].[FK_VENDEDORCOMPROBANTE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[COMPROBANTE] DROP CONSTRAINT [FK_VENDEDORCOMPROBANTE];
GO
IF OBJECT_ID(N'[dbo].[FK_VENDOREMPRESA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[VENDEDOR] DROP CONSTRAINT [FK_VENDOREMPRESA];
GO

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[ARTICULO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[ARTICULO];
GO
IF OBJECT_ID(N'[dbo].[ARTICULOCOMPONENTE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[ARTICULOCOMPONENTE];
GO
IF OBJECT_ID(N'[dbo].[ARTICULOIMPUESTO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[ARTICULOIMPUESTO];
GO
IF OBJECT_ID(N'[dbo].[BODEGA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[BODEGA];
GO
IF OBJECT_ID(N'[dbo].[BODEGASTOCK]', 'U') IS NOT NULL
    DROP TABLE [dbo].[BODEGASTOCK];
GO
IF OBJECT_ID(N'[dbo].[CLIENTE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CLIENTE];
GO
IF OBJECT_ID(N'[dbo].[COMPROBANTE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[COMPROBANTE];
GO
IF OBJECT_ID(N'[dbo].[COMPROBANTEFORMAPAGO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[COMPROBANTEFORMAPAGO];
GO
IF OBJECT_ID(N'[dbo].[CONDICIONPAGO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[CONDICIONPAGO];
GO
IF OBJECT_ID(N'[dbo].[DETALLECOMPROBANTE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[DETALLECOMPROBANTE];
GO
IF OBJECT_ID(N'[dbo].[DETALLELISTADEPRECIO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[DETALLELISTADEPRECIO];
GO
IF OBJECT_ID(N'[dbo].[ELEMENTO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[ELEMENTO];
GO
IF OBJECT_ID(N'[dbo].[EMPRESA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[EMPRESA];
GO
IF OBJECT_ID(N'[dbo].[ESTABLECIMIENTO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[ESTABLECIMIENTO];
GO
IF OBJECT_ID(N'[dbo].[ESTADOCOMPROBANTE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[ESTADOCOMPROBANTE];
GO
IF OBJECT_ID(N'[dbo].[FORMAPAGO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[FORMAPAGO];
GO
IF OBJECT_ID(N'[dbo].[IMPUESTO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[IMPUESTO];
GO
IF OBJECT_ID(N'[dbo].[IMPUESTOCOMPROBANTE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[IMPUESTOCOMPROBANTE];
GO
IF OBJECT_ID(N'[dbo].[LISTADEPRECIO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[LISTADEPRECIO];
GO
IF OBJECT_ID(N'[dbo].[PARAMETRO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PARAMETRO];
GO
IF OBJECT_ID(N'[dbo].[PRODUCTO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PRODUCTO];
GO
IF OBJECT_ID(N'[dbo].[PROVEEDOR]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PROVEEDOR];
GO
IF OBJECT_ID(N'[dbo].[PROVEEDORCERTIFICADO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PROVEEDORCERTIFICADO];
GO
IF OBJECT_ID(N'[dbo].[PUNTOEMISION]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PUNTOEMISION];
GO
IF OBJECT_ID(N'[dbo].[PUNTOEMISIONAUTORIZACION]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PUNTOEMISIONAUTORIZACION];
GO
IF OBJECT_ID(N'[dbo].[PUNTOEMISIONDOCUMENTO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PUNTOEMISIONDOCUMENTO];
GO
IF OBJECT_ID(N'[dbo].[SOCIONEGOCIO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[SOCIONEGOCIO];
GO
IF OBJECT_ID(N'[dbo].[TABLAIMPUESTOS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TABLAIMPUESTOS];
GO
IF OBJECT_ID(N'[dbo].[TIPOAMBIENTE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TIPOAMBIENTE];
GO
IF OBJECT_ID(N'[dbo].[TIPOARTICULO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TIPOARTICULO];
GO
IF OBJECT_ID(N'[dbo].[TIPOCOMPROBANTE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TIPOCOMPROBANTE];
GO
IF OBJECT_ID(N'[dbo].[TIPOELEMENTO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TIPOELEMENTO];
GO
IF OBJECT_ID(N'[dbo].[TIPOESTADO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TIPOESTADO];
GO
IF OBJECT_ID(N'[dbo].[TIPOFORMAPAGO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TIPOFORMAPAGO];
GO
IF OBJECT_ID(N'[dbo].[TIPOIDENTIFICACION]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TIPOIDENTIFICACION];
GO
IF OBJECT_ID(N'[dbo].[TIPOIMPUESTO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TIPOIMPUESTO];
GO
IF OBJECT_ID(N'[dbo].[UNIDAD]', 'U') IS NOT NULL
    DROP TABLE [dbo].[UNIDAD];
GO
IF OBJECT_ID(N'[dbo].[UNIDADTIEMPO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[UNIDADTIEMPO];
GO
IF OBJECT_ID(N'[dbo].[USUARIO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[USUARIO];
GO
IF OBJECT_ID(N'[dbo].[USUARIOEMPRESA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[USUARIOEMPRESA];
GO
IF OBJECT_ID(N'[dbo].[VENDEDOR]', 'U') IS NOT NULL
    DROP TABLE [dbo].[VENDEDOR];
GO
IF OBJECT_ID(N'[ModelStoreContainer].[V_SOCIONEGOCIO]', 'U') IS NOT NULL
    DROP TABLE [ModelStoreContainer].[V_SOCIONEGOCIO];
GO

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'ARTICULO'
CREATE TABLE [dbo].[ARTICULO] (
    [CODIGOEMPRESA] bigint  NOT NULL,
    [CODIGOARTICULO] bigint IDENTITY(1,1) NOT NULL,
    [CODIGO] varchar(50)  NOT NULL,
    [DESCRIPCION] varchar(100)  NOT NULL,
    [COSTO] decimal(18,2)  NOT NULL,
    [PRECIOVENTA] decimal(18,2)  NOT NULL,
    [CANTIDAD] decimal(18,2)  NOT NULL,
    [CODIGOIMPUESTO] bigint  NOT NULL,
    [ESTADO] varchar(1)  NOT NULL,
    [CODIGOUNIDAD] bigint  NULL,
    [SECCION] varchar(20)  NULL,
    [INGRESOS] decimal(18,2)  NULL,
    [EGRESOS] decimal(18,2)  NULL,
    [SALDOINICIAL] decimal(18,2)  NULL,
    [DESCRIPCIONCORTA] varchar(100)  NULL,
    [STOCKMINIMO] decimal(18,2)  NULL,
    [STOCKMAXIMO] decimal(18,2)  NULL,
    [ENPANTALLA] varchar(1)  NULL,
    [GRAFICO] varbinary(max)  NULL,
    [CODIGOTIPOARTICULO] bigint  NOT NULL,
    [SOLOCOMPRAS] varchar(1)  NULL,
    [VENTAS] varchar(1)  NULL,
    [INVENTARIO] varchar(1)  NULL,
    [FECHACREACION] datetime  NOT NULL,
    [FECHAMODIFICACION] datetime  NOT NULL,
    [PRECIOVARIABLE] varchar(1)  NULL
);
GO

-- Creating table 'ARTICULOCOMPONENTE'
CREATE TABLE [dbo].[ARTICULOCOMPONENTE] (
    [CODIGOARTICULOCOMPONENTE] bigint IDENTITY(1,1) NOT NULL,
    [CODIGOARTICULO] bigint  NULL,
    [CANTIDAD] decimal(18,4)  NULL,
    [CODIGOUNIDAD] bigint  NULL,
    [ESTADO] varchar(1)  NULL,
    [CODIGOARTICULOCOMP] bigint  NULL
);
GO

-- Creating table 'ARTICULOIMPUESTO'
CREATE TABLE [dbo].[ARTICULOIMPUESTO] (
    [CODIGOARTICULOIMPUESTO] bigint IDENTITY(1,1) NOT NULL,
    [CODIGOARTICULO] bigint  NOT NULL,
    [CODIGOIMPUESTO] bigint  NOT NULL
);
GO

-- Creating table 'BODEGA'
CREATE TABLE [dbo].[BODEGA] (
    [CODIGOBODEGA] bigint IDENTITY(1,1) NOT NULL,
    [CODIGOEMPRESA] bigint  NOT NULL,
    [NOMBRE] varchar(100)  NOT NULL,
    [CODIGOESTABLECIMIENTO] bigint  NOT NULL
);
GO

-- Creating table 'BODEGASTOCK'
CREATE TABLE [dbo].[BODEGASTOCK] (
    [CODIGOBODEGASTOCK] bigint IDENTITY(1,1) NOT NULL,
    [CODIGOBODEGA] bigint  NOT NULL,
    [CODIGOARTICULO] bigint  NOT NULL,
    [STOCKACTUAL] decimal(18,4)  NOT NULL,
    [PRECIO] decimal(18,4)  NOT NULL,
    [COSTO] decimal(18,4)  NOT NULL
);
GO

-- Creating table 'CLIENTE'
CREATE TABLE [dbo].[CLIENTE] (
    [CODIGOCLIENTE] bigint IDENTITY(1,1) NOT NULL,
    [CODIGOSOCIONEGOCIO] bigint  NOT NULL,
    [CODIGOEMPRESA] bigint  NULL,
    [APLICAIVA] varchar(1)  NOT NULL,
    [LIMITECREDITO] decimal(18,2)  NULL,
    [LISTAPRECIO] varchar(1)  NULL,
    [TIPOCLIENTE] varchar(1)  NULL,
    [PORCENTAJEDESCUENTO] decimal(18,2)  NULL,
    [CODIGOSUB] varchar(8)  NULL,
    [NUMEROPAGO] bigint  NULL,
    [PLAZOPAGO] bigint  NULL,
    [SALDO] decimal(18,2)  NULL,
    [FORMAPAGO] varchar(1)  NULL,
    [GRUPOCLIENTE] varchar(3)  NULL,
    [TIPO] char(1)  NULL,
    [FECHACORTE] datetime  NULL,
    [SECTOR] varchar(8)  NULL,
    [RISE] varchar(40)  NULL,
    [PARTERELACIONADA] varchar(2)  NULL
);
GO

-- Creating table 'COMPROBANTE'
CREATE TABLE [dbo].[COMPROBANTE] (
    [CODIGOCOMPROBANTE] bigint IDENTITY(1,1) NOT NULL,
    [CODIGOEMPRESA] bigint  NOT NULL,
    [CODIGOTIPOCOMPROBANTE] bigint  NOT NULL,
    [CODIGOPUNTOEMISION] bigint  NOT NULL,
    [CODIGOESTABLECIMIENTO] bigint  NOT NULL,
    [NUMEROCOMPROBANTE] bigint  NOT NULL,
    [FECHAEMISION] datetime  NOT NULL,
    [CODIGOSOCIONEGOCIO] bigint  NULL,
    [TOTALSINIMPUESTO] decimal(18,2)  NOT NULL,
    [TOTAL] decimal(18,4)  NOT NULL,
    [CODIGOLISTADEPRECIO] bigint  NULL,
    [DESCUENTOADICIONAL] decimal(18,2)  NULL,
    [ESTADO] int  NOT NULL,
    [OBSERVACION] varchar(300)  NULL,
    [PAGADO] int  NULL,
    [INFORMACIONADICIONAL] varchar(300)  NULL,
    [CODIGOVENDEDOR] bigint  NULL,
    [CODIGOESTADOCOMPROBANTE] bigint  NOT NULL,
    [CLAVEDEACCESO] varchar(100)  NULL,
    [AUTORIZACION] varchar(100)  NULL,
    [ARCHIVOAUTORIZADO] varbinary(max)  NULL,
    [VALORRECIBIDO] decimal(18,4)  NULL,
    [CAMBIO] decimal(18,2)  NULL,
    [CODIGOBODEGA] bigint  NULL,
    [NOVEDAD] nvarchar(max)  NULL,
    [FECHAAUTORIZACION] datetime  NULL
);
GO

-- Creating table 'COMPROBANTEFORMAPAGO'
CREATE TABLE [dbo].[COMPROBANTEFORMAPAGO] (
    [CODIGOCOMPROBANTEFORMAPAGO] bigint IDENTITY(1,1) NOT NULL,
    [CODIGOFORMAPAGO] bigint  NOT NULL,
    [VALOR] decimal(18,4)  NOT NULL,
    [OBSERVACION] varchar(300)  NULL,
    [CODIGOCOMPROBANTE] bigint  NOT NULL,
    [PLAZO] int  NOT NULL,
    [CODIGOUNIDADTIEMPO] bigint  NOT NULL
);
GO

-- Creating table 'CONDICIONPAGO'
CREATE TABLE [dbo].[CONDICIONPAGO] (
    [CODIGOCONDICIONPAGO] char(255)  NOT NULL,
    [PRECIONORMAL] char(1)  NULL,
    [DIASCREDITO] int  NULL
);
GO

-- Creating table 'DETALLECOMPROBANTE'
CREATE TABLE [dbo].[DETALLECOMPROBANTE] (
    [CODIGODETALLECOMPROBANTE] bigint IDENTITY(1,1) NOT NULL,
    [CODIGOCOMPROBANTE] bigint  NOT NULL,
    [NUMEROCOMPROBANTE] int  NOT NULL,
    [NUMEROLINEA] int  NOT NULL,
    [CODIGOARTICULO] bigint  NOT NULL,
    [DESCRIPCIONARTICULO] varchar(300)  NOT NULL,
    [CANTIDAD] decimal(18,4)  NOT NULL,
    [PVP] decimal(18,4)  NOT NULL,
    [DESCUENTO] decimal(19,2)  NULL,
    [PORCENTAJEDESCUENTO] decimal(19,2)  NULL,
    [ESTADO] int  NOT NULL,
    [CODIGOESTABLECIMIENTO] bigint  NOT NULL,
    [CODIGOPUNTOEMISION] bigint  NOT NULL,
    [CODIGOTIPODOCUMENTO] bigint  NOT NULL,
    [CODIGOIMPUESTO] bigint  NOT NULL,
    [PORCENTAJEIMPUESTO] decimal(14,2)  NOT NULL,
    [VALORIMPUESTO] decimal(18,2)  NULL,
    [BASEIMPONIBLE] decimal(18,2)  NULL,
    [TOTAL] decimal(18,2)  NULL,
    [CODIGOBODEGA] bigint  NOT NULL
);
GO

-- Creating table 'DETALLELISTADEPRECIO'
CREATE TABLE [dbo].[DETALLELISTADEPRECIO] (
    [CODIGODETALLELISTAPRECIO] bigint  NOT NULL,
    [CODIGOLISTADEPRECIO] bigint  NOT NULL,
    [CODIGOARTICULO] bigint  NOT NULL,
    [PRECIO] decimal(18,4)  NOT NULL,
    [FECHADESDE] datetime  NULL,
    [FECHAHASTA] datetime  NULL
);
GO

-- Creating table 'ELEMENTO'
CREATE TABLE [dbo].[ELEMENTO] (
    [CODIGOELEMENTO] bigint IDENTITY(1,1) NOT NULL,
    [NOMBRE] varchar(50)  NULL,
    [GRAFICO] varchar(100)  NULL,
    [ORDEN] int  NULL,
    [CODIGOTIPOELEMENTO] bigint  NULL,
    [TIPO] varchar(10)  NULL,
    [ACCION] varchar(100)  NULL,
    [codigoelemento_] bigint  NULL
);
GO

-- Creating table 'EMPRESA'
CREATE TABLE [dbo].[EMPRESA] (
    [CODIGOEMPRESA] bigint IDENTITY(1,1) NOT NULL,
    [NOMBRE] varchar(60)  NOT NULL,
    [DIRECCION1] varchar(70)  NULL,
    [TELEFONO1] varchar(70)  NULL,
    [DIRECCION2] varchar(70)  NULL,
    [TELEFONO2] varchar(70)  NULL,
    [RUC] varchar(15)  NULL,
    [DURACIONDIA] int  NULL,
    [LUGAR] varchar(20)  NULL,
    [FAC] varchar(20)  NULL,
    [MASCTA] varchar(20)  NULL,
    [CIUDAD] char(20)  NULL,
    [INICIOPERIODO] datetime  NULL,
    [FINPERIODO] datetime  NULL,
    [PERIODO] varchar(4)  NULL,
    [CODIGOCUENTA] varchar(50)  NULL,
    [CUENTAINGRESO] varchar(50)  NULL,
    [CUENTAGASTO] varchar(50)  NULL,
    [FECHACIERRE] datetime  NULL,
    [CODIGOUSUARIO] varchar(10)  NULL,
    [FECHAACTUALIZACION] datetime  NULL,
    [EMPRESAACT] varchar(10)  NULL,
    [EMPRESACON] varchar(1)  NULL,
    [CUENTAACTIVO] varchar(10)  NULL,
    [CUENTAPASIVO] varchar(10)  NULL,
    [CUENTAPATRIMONIO] varchar(10)  NULL,
    [CODIGOMONEDA] varchar(2)  NOT NULL,
    [FECHACAL] datetime  NULL,
    [TIPO] varchar(1)  NULL,
    [CORREOELECTRONICO] varchar(60)  NULL,
    [IDENTIFICACIONREPRESENTANTE] varchar(10)  NULL,
    [RUCCONTADOR] varchar(13)  NULL,
    [TIPOIDENTIFICACIONREPRESENTANTE] varchar(2)  NULL,
    [AUTORIZACION] varchar(15)  NULL,
    [CUENTAGASTO2] varchar(10)  NULL,
    [CUENTAORDEN] varchar(10)  NULL,
    [CUENTAORDEN2] varchar(10)  NULL,
    [TIPOCUENTAS] varchar(2)  NULL,
    [CODIGOENTIDAD] varchar(7)  NULL,
    [NUMESTABLECIMIENTOS] varchar(3)  NULL,
    [FIRMAELECTRONICA] varbinary(max)  NULL,
    [ESTABLECIMIENTO] varchar(3)  NULL,
    [CLAVEFIRMA] varchar(50)  NULL,
    [LOGO] varbinary(max)  NULL,
    [NOMBRECOMERCIAL] varchar(200)  NULL,
    [CODIGOTIPOAMBIENTE] bigint  NULL,
    [CONTRIBUYENTEESPECIAL] varchar(2)  NULL,
    [LLEVACONTABILIDAD] varchar(2)  NULL,
    [NUMERORESOLUCION] varchar(5)  NULL,
    [FECHACADUCIDAD] datetime  NULL,
    [CODIGOPROVEEDORCERTIFICADO] int  NULL
);
GO

-- Creating table 'ESTABLECIMIENTO'
CREATE TABLE [dbo].[ESTABLECIMIENTO] (
    [CODIGOESTABLECIMIENTO] bigint IDENTITY(1,1) NOT NULL,
    [CODIGOEMPRESA] bigint  NULL,
    [NUMERO] varchar(3)  NULL,
    [DIRECCION] varchar(300)  NULL
);
GO

-- Creating table 'ESTADOCOMPROBANTE'
CREATE TABLE [dbo].[ESTADOCOMPROBANTE] (
    [CODIGOESTADOCOMPROBANTE] bigint  NOT NULL,
    [CODIGOTIPOESTADO] int  NULL,
    [DESCRIPCION] varchar(100)  NULL
);
GO

-- Creating table 'FORMAPAGO'
CREATE TABLE [dbo].[FORMAPAGO] (
    [CODIGOFORMAPAGO] bigint IDENTITY(1,1) NOT NULL,
    [DESCRIPCION] varchar(50)  NOT NULL,
    [CODIGOTIPOFORMAPAGO] bigint  NOT NULL,
    [CODIGOEMPRESA] bigint  NOT NULL
);
GO

-- Creating table 'IMPUESTO'
CREATE TABLE [dbo].[IMPUESTO] (
    [CODIGOIMPUESTO] bigint IDENTITY(1,1) NOT NULL,
    [CODIGOTIPOIMPUESTO] int  NOT NULL,
    [PORCENTAJE] decimal(14,2)  NOT NULL,
    [DESCRIPCION] varchar(254)  NOT NULL,
    [FECHADESDE] datetime  NULL,
    [FECHAHASTA] datetime  NULL,
    [CODIGOSRI] char(2)  NULL,
    [DESGLOSADO] varchar(1)  NOT NULL,
    [CODIGOEMPRESA] bigint  NULL,
    [ESTADO] varchar(1)  NOT NULL
);
GO

-- Creating table 'IMPUESTOCOMPROBANTE'
CREATE TABLE [dbo].[IMPUESTOCOMPROBANTE] (
    [CODIGOIMPUESTOCOMPROBANTE] bigint IDENTITY(1,1) NOT NULL,
    [CODIGOCOMPROBANTE] bigint  NOT NULL,
    [CODIGOIMPUESTO] bigint  NOT NULL,
    [PORCENTAJE] decimal(18,2)  NOT NULL,
    [VALORIMPUESTO] decimal(18,2)  NOT NULL,
    [BASEIMPONIBLE] decimal(18,2)  NOT NULL
);
GO

-- Creating table 'LISTADEPRECIO'
CREATE TABLE [dbo].[LISTADEPRECIO] (
    [CODIGOLISTADEPRECIO] bigint IDENTITY(1,1) NOT NULL,
    [DESCRIPCION] varchar(100)  NOT NULL,
    [CODIGOEMPRESA] bigint  NOT NULL,
    [CODIGOSOCIONEGOCIO] bigint  NULL
);
GO

-- Creating table 'PARAMETRO'
CREATE TABLE [dbo].[PARAMETRO] (
    [CODIGOPARAMETRO] bigint IDENTITY(1,1) NOT NULL,
    [NOMBRE] varchar(100)  NULL,
    [VALORSTRING] varchar(255)  NULL,
    [VALORNUMERO] int  NULL,
    [VALORFECHA] datetime  NULL,
    [VALORDECIMAL] float  NULL,
    [VALORBLOB] varbinary(max)  NULL,
    [TIPO] char(3)  NULL,
    [DESCRIPCION] char(250)  NULL,
    [CODIGOEMPRESA] bigint  NOT NULL
);
GO

-- Creating table 'PRODUCTO'
CREATE TABLE [dbo].[PRODUCTO] (
    [CODIGO] int  NOT NULL,
    [CODIGO_PRINCIPAL] varchar(70)  NULL,
    [CODIGO_AUXILIAR] varchar(70)  NULL,
    [NOMBRE] varchar(100)  NULL,
    [VALOR_UNITARIO] decimal(18,4)  NULL,
    [TIPO_PRODUCTO] varchar(1)  NULL,
    [IVA] varchar(1)  NULL,
    [ICE] varchar(1)  NULL,
    [IRBPNR] char(1)  NULL
);
GO

-- Creating table 'PROVEEDOR'
CREATE TABLE [dbo].[PROVEEDOR] (
    [CODIGOPROVEEDOR] bigint IDENTITY(1,1) NOT NULL,
    [CODIGOSOCIONEGOCIO] bigint  NULL,
    [CODIGOEMPRESA] bigint  NULL,
    [CODIGOCUENTA] varchar(20)  NULL,
    [CODIGOCLASE] varchar(5)  NULL,
    [APLICAIVA] varchar(1)  NULL,
    [ESTATUS] varchar(1)  NULL,
    [LIMITECREDITO] decimal(10,2)  NULL,
    [CODIGOUSUARIO] varchar(10)  NULL,
    [FECHAACTUALIZACION] datetime  NULL,
    [PLANPAGO] bigint  NULL,
    [NUMEROPAGO] bigint  NULL,
    [DESCHEQUE] varchar(80)  NULL,
    [CONTRATO] varchar(30)  NULL,
    [TIPOPROVEEDOR] varchar(1)  NULL,
    [CUENTABANCO] varchar(30)  NULL,
    [BANCO] varchar(5)  NULL,
    [CODIGOTIPO] varchar(3)  NULL,
    [FECHAEMISION] datetime  NULL,
    [FECHAVALIDEZ] datetime  NULL,
    [NUMEROCONTRIBUYENTE] varchar(50)  NULL,
    [NUMEROIMPRENTA] varchar(20)  NULL,
    [SERIE] varchar(6)  NULL,
    [CONTRIBUYENTESRI] varchar(1)  NULL
);
GO

-- Creating table 'PROVEEDORCERTIFICADO'
CREATE TABLE [dbo].[PROVEEDORCERTIFICADO] (
    [CODIGOPROVEEDORCERTIFICADO] int IDENTITY(1,1) NOT NULL,
    [DESCRIPCION] varchar(254)  NULL,
    [SIGLA] varchar(45)  NULL
);
GO

-- Creating table 'PUNTOEMISION'
CREATE TABLE [dbo].[PUNTOEMISION] (
    [CODIGOPUNTOEMISION] bigint IDENTITY(1,1) NOT NULL,
    [NOMBRE] varchar(3)  NULL,
    [SERIE] varchar(100)  NULL,
    [CODIGOESTABLECIMIENTO] bigint  NULL,
    [ELECTRONICO] varchar(1)  NULL,
    [DIRECTORIOREPORTES] varchar(255)  NULL,
    [ARCHIVOREPORTE] varbinary(max)  NULL
);
GO

-- Creating table 'PUNTOEMISIONAUTORIZACION'
CREATE TABLE [dbo].[PUNTOEMISIONAUTORIZACION] (
    [CODIGOPUNTOEMISIONAUTORIZACION] bigint IDENTITY(1,1) NOT NULL,
    [CODIGOPUNTOEMISIONDOCUMENTO] bigint  NOT NULL,
    [FECHAINICIAL] datetime  NOT NULL,
    [FECHAFINAL] datetime  NOT NULL,
    [AUTORIZACION] varchar(100)  NULL
);
GO

-- Creating table 'PUNTOEMISIONDOCUMENTO'
CREATE TABLE [dbo].[PUNTOEMISIONDOCUMENTO] (
    [CODIGOPUNTOEMISIONDOCUMENTO] bigint IDENTITY(1,1) NOT NULL,
    [CODIGOPUNTOEMISION] bigint  NULL,
    [CODIGOTIPOCOMPROBANTE] bigint  NULL,
    [NUMERODOCUMENTO] bigint  NULL,
    [NUMEROPENDIENTE] bigint  NULL,
    [ARCHIVOREPORTE] varbinary(max)  NULL
);
GO

-- Creating table 'SOCIONEGOCIO'
CREATE TABLE [dbo].[SOCIONEGOCIO] (
    [CODIGOSOCIONEGOCIO] bigint IDENTITY(1,1) NOT NULL,
    [RAZONSOCIAL] varchar(300)  NULL,
    [NUMERODOCUMENTO] varchar(15)  NULL,
    [DIRECCION] varchar(120)  NULL,
    [DIRECCION2] varchar(120)  NULL,
    [TELEFONO] varchar(20)  NULL,
    [TELEFONO2] varchar(20)  NULL,
    [FAX] varchar(10)  NULL,
    [CONTACTO] varchar(30)  NULL,
    [ESTATUS] varchar(1)  NULL,
    [CODIGOUSUARIO] varchar(10)  NULL,
    [FECHAACTUALIZACION] datetime  NULL,
    [CIUDAD] varchar(70)  NULL,
    [EMAIL] varchar(120)  NULL,
    [COMENTARIO] varchar(60)  NULL,
    [CODIGOPROVINCIA] varchar(4)  NULL,
    [ESTADOCIVIL] varchar(1)  NULL,
    [FECHANACIMIENTO] datetime  NULL,
    [NOMBRECOMERCIAL] varchar(300)  NULL,
    [SUELDO] decimal(20,4)  NULL,
    [CODIGOTIPOIDENTIFICACION] bigint  NULL
);
GO

-- Creating table 'TABLAIMPUESTOS'
CREATE TABLE [dbo].[TABLAIMPUESTOS] (
    [Id] decimal(18,0) IDENTITY(1,1) NOT NULL,
    [Tipo] int  NULL,
    [Descripcion] char(255)  NULL,
    [Codigo] char(255)  NULL,
    [Porcentaje] int  NULL,
    [CodigoAlterno] char(255)  NULL
);
GO

-- Creating table 'TIPOAMBIENTE'
CREATE TABLE [dbo].[TIPOAMBIENTE] (
    [CODIGOTIPOAMBIENTE] bigint  NOT NULL,
    [DESCRIPCION] varchar(254)  NULL
);
GO

-- Creating table 'TIPOARTICULO'
CREATE TABLE [dbo].[TIPOARTICULO] (
    [CODIGOTIPOARTICULO] bigint  NOT NULL,
    [NOMBRE] varchar(50)  NULL,
    [CONTROLASTOCK] varchar(1)  NULL
);
GO

-- Creating table 'TIPOCOMPROBANTE'
CREATE TABLE [dbo].[TIPOCOMPROBANTE] (
    [CODIGOTIPOCOMPROBANTE] bigint  NOT NULL,
    [CODIGOSRI] varchar(10)  NULL,
    [NOMBRE] varchar(254)  NULL,
    [AFECTAINVENTARIO] varchar(1)  NULL,
    [FORMATO] varchar(255)  NOT NULL,
    [SIGNO] varchar(1)  NULL,
    [VERSION] varchar(10)  NULL,
    [ARCHIVOREPORTE] varbinary(max)  NULL
);
GO

-- Creating table 'TIPOELEMENTO'
CREATE TABLE [dbo].[TIPOELEMENTO] (
    [CODIGOTIPOELEMENTO] bigint IDENTITY(1,1) NOT NULL,
    [NOMBRE] varchar(50)  NULL
);
GO

-- Creating table 'TIPOESTADO'
CREATE TABLE [dbo].[TIPOESTADO] (
    [CODIGOTIPOESTADO] int  NOT NULL,
    [DESCRIPCION] varchar(100)  NULL
);
GO

-- Creating table 'TIPOFORMAPAGO'
CREATE TABLE [dbo].[TIPOFORMAPAGO] (
    [CODIGOTIPOFORMAPAGO] bigint IDENTITY(1,1) NOT NULL,
    [DESCRIPCION] varchar(300)  NULL,
    [CODIGOSRI] varchar(3)  NULL
);
GO

-- Creating table 'TIPOIDENTIFICACION'
CREATE TABLE [dbo].[TIPOIDENTIFICACION] (
    [CODIGOTIPOIDENTIFICACION] bigint  NOT NULL,
    [NOMBRE] varchar(50)  NOT NULL,
    [TIPOIDENTIFICACIONSRI] varchar(2)  NOT NULL
);
GO

-- Creating table 'TIPOIMPUESTO'
CREATE TABLE [dbo].[TIPOIMPUESTO] (
    [CODIGOTIPOIMPUESTO] int  NOT NULL,
    [DESCRIPCION] varchar(254)  NOT NULL
);
GO

-- Creating table 'UNIDAD'
CREATE TABLE [dbo].[UNIDAD] (
    [CODIGOUNIDAD] bigint IDENTITY(1,1) NOT NULL,
    [CODIGOEMPRESA] bigint  NOT NULL,
    [DESCRIPCION] varchar(50)  NOT NULL
);
GO

-- Creating table 'UNIDADTIEMPO'
CREATE TABLE [dbo].[UNIDADTIEMPO] (
    [CODIGOUNIDADTIEMPO] bigint IDENTITY(1,1) NOT NULL,
    [DESCRIPCION] varchar(100)  NOT NULL,
    [NUMERODIAS] int  NOT NULL
);
GO

-- Creating table 'USUARIO'
CREATE TABLE [dbo].[USUARIO] (
    [CODIGOUSUARIO] bigint IDENTITY(1,1) NOT NULL,
    [TIPOUSUARIO] varchar(1)  NOT NULL,
    [CLAVE] varchar(10)  NOT NULL,
    [NOMBRE] varchar(30)  NOT NULL,
    [FECHAINGRESO] datetime  NULL,
    [FECHAEXPIDE] datetime  NULL,
    [TIPOACCESO] varchar(1)  NULL,
    [FECHAACTUALIZACION] datetime  NULL,
    [NOMBRECOMPLETO] varchar(200)  NULL,
    [CONECTADO] varchar(1)  NULL
);
GO

-- Creating table 'USUARIOEMPRESA'
CREATE TABLE [dbo].[USUARIOEMPRESA] (
    [CODIGOUSUARIOEMPRESA] bigint IDENTITY(1,1) NOT NULL,
    [CODIGOUSUARIO] bigint  NOT NULL,
    [CODIGOEMPRESA] bigint  NOT NULL,
    [CODIGOESTADO] bigint  NULL,
    [CODIGOESTABLECIMIENTO] bigint  NULL,
    [CENTROCOSTO] varchar(20)  NULL,
    [TIPO_CO] varchar(2)  NULL,
    [TIPO_FC] varchar(2)  NULL,
    [TIPO_FV] varchar(2)  NULL,
    [TIPO_PP] varchar(2)  NULL,
    [TIPO_CC] varchar(2)  NULL,
    [SUPERVISOR] varchar(1)  NULL
);
GO

-- Creating table 'VENDEDOR'
CREATE TABLE [dbo].[VENDEDOR] (
    [CODIGOVENDEDOR] bigint IDENTITY(1,1) NOT NULL,
    [CODIGOEMPRESA] bigint  NULL,
    [SIGLA] varchar(5)  NULL,
    [CODIGOSOCIONEGOCIO] bigint  NULL
);
GO

-- Creating table 'V_SOCIONEGOCIO'
CREATE TABLE [dbo].[V_SOCIONEGOCIO] (
    [TIPOSOCIONEGOCIO] int  NOT NULL,
    [CODIGOSOCIONEGOCIO] bigint  NOT NULL,
    [RAZONSOCIAL] varchar(300)  NULL,
    [NUMERODOCUMENTO] varchar(15)  NULL,
    [CODIGOEMPRESA] bigint  NULL,
    [DIRECCION] varchar(120)  NULL,
    [TELEFONO] varchar(20)  NULL,
    [EMAIL] varchar(120)  NULL,
    [COMENTARIO] varchar(60)  NULL,
    [NOMBRECOMERCIAL] varchar(300)  NULL,
    [CODIGOTIPOIDENTIFICACION] bigint  NULL,
    [CODIGO] bigint  NOT NULL,
    [ESTATUS] varchar(1)  NULL
);
GO

-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on [CODIGOARTICULO] in table 'ARTICULO'
ALTER TABLE [dbo].[ARTICULO]
ADD CONSTRAINT [PK_ARTICULO]
    PRIMARY KEY CLUSTERED ([CODIGOARTICULO] ASC);
GO

-- Creating primary key on [CODIGOARTICULOCOMPONENTE] in table 'ARTICULOCOMPONENTE'
ALTER TABLE [dbo].[ARTICULOCOMPONENTE]
ADD CONSTRAINT [PK_ARTICULOCOMPONENTE]
    PRIMARY KEY CLUSTERED ([CODIGOARTICULOCOMPONENTE] ASC);
GO

-- Creating primary key on [CODIGOARTICULOIMPUESTO] in table 'ARTICULOIMPUESTO'
ALTER TABLE [dbo].[ARTICULOIMPUESTO]
ADD CONSTRAINT [PK_ARTICULOIMPUESTO]
    PRIMARY KEY CLUSTERED ([CODIGOARTICULOIMPUESTO] ASC);
GO

-- Creating primary key on [CODIGOBODEGA] in table 'BODEGA'
ALTER TABLE [dbo].[BODEGA]
ADD CONSTRAINT [PK_BODEGA]
    PRIMARY KEY CLUSTERED ([CODIGOBODEGA] ASC);
GO

-- Creating primary key on [CODIGOBODEGASTOCK] in table 'BODEGASTOCK'
ALTER TABLE [dbo].[BODEGASTOCK]
ADD CONSTRAINT [PK_BODEGASTOCK]
    PRIMARY KEY CLUSTERED ([CODIGOBODEGASTOCK] ASC);
GO

-- Creating primary key on [CODIGOCLIENTE], [CODIGOSOCIONEGOCIO], [APLICAIVA] in table 'CLIENTE'
ALTER TABLE [dbo].[CLIENTE]
ADD CONSTRAINT [PK_CLIENTE]
    PRIMARY KEY CLUSTERED ([CODIGOCLIENTE], [CODIGOSOCIONEGOCIO], [APLICAIVA] ASC);
GO

-- Creating primary key on [CODIGOCOMPROBANTE] in table 'COMPROBANTE'
ALTER TABLE [dbo].[COMPROBANTE]
ADD CONSTRAINT [PK_COMPROBANTE]
    PRIMARY KEY CLUSTERED ([CODIGOCOMPROBANTE] ASC);
GO

-- Creating primary key on [CODIGOCOMPROBANTEFORMAPAGO] in table 'COMPROBANTEFORMAPAGO'
ALTER TABLE [dbo].[COMPROBANTEFORMAPAGO]
ADD CONSTRAINT [PK_COMPROBANTEFORMAPAGO]
    PRIMARY KEY CLUSTERED ([CODIGOCOMPROBANTEFORMAPAGO] ASC);
GO

-- Creating primary key on [CODIGOCONDICIONPAGO] in table 'CONDICIONPAGO'
ALTER TABLE [dbo].[CONDICIONPAGO]
ADD CONSTRAINT [PK_CONDICIONPAGO]
    PRIMARY KEY CLUSTERED ([CODIGOCONDICIONPAGO] ASC);
GO

-- Creating primary key on [CODIGODETALLECOMPROBANTE] in table 'DETALLECOMPROBANTE'
ALTER TABLE [dbo].[DETALLECOMPROBANTE]
ADD CONSTRAINT [PK_DETALLECOMPROBANTE]
    PRIMARY KEY CLUSTERED ([CODIGODETALLECOMPROBANTE] ASC);
GO

-- Creating primary key on [CODIGODETALLELISTAPRECIO] in table 'DETALLELISTADEPRECIO'
ALTER TABLE [dbo].[DETALLELISTADEPRECIO]
ADD CONSTRAINT [PK_DETALLELISTADEPRECIO]
    PRIMARY KEY CLUSTERED ([CODIGODETALLELISTAPRECIO] ASC);
GO

-- Creating primary key on [CODIGOELEMENTO] in table 'ELEMENTO'
ALTER TABLE [dbo].[ELEMENTO]
ADD CONSTRAINT [PK_ELEMENTO]
    PRIMARY KEY CLUSTERED ([CODIGOELEMENTO] ASC);
GO

-- Creating primary key on [CODIGOEMPRESA] in table 'EMPRESA'
ALTER TABLE [dbo].[EMPRESA]
ADD CONSTRAINT [PK_EMPRESA]
    PRIMARY KEY CLUSTERED ([CODIGOEMPRESA] ASC);
GO

-- Creating primary key on [CODIGOESTABLECIMIENTO] in table 'ESTABLECIMIENTO'
ALTER TABLE [dbo].[ESTABLECIMIENTO]
ADD CONSTRAINT [PK_ESTABLECIMIENTO]
    PRIMARY KEY CLUSTERED ([CODIGOESTABLECIMIENTO] ASC);
GO

-- Creating primary key on [CODIGOESTADOCOMPROBANTE] in table 'ESTADOCOMPROBANTE'
ALTER TABLE [dbo].[ESTADOCOMPROBANTE]
ADD CONSTRAINT [PK_ESTADOCOMPROBANTE]
    PRIMARY KEY CLUSTERED ([CODIGOESTADOCOMPROBANTE] ASC);
GO

-- Creating primary key on [CODIGOFORMAPAGO] in table 'FORMAPAGO'
ALTER TABLE [dbo].[FORMAPAGO]
ADD CONSTRAINT [PK_FORMAPAGO]
    PRIMARY KEY CLUSTERED ([CODIGOFORMAPAGO] ASC);
GO

-- Creating primary key on [CODIGOIMPUESTO] in table 'IMPUESTO'
ALTER TABLE [dbo].[IMPUESTO]
ADD CONSTRAINT [PK_IMPUESTO]
    PRIMARY KEY CLUSTERED ([CODIGOIMPUESTO] ASC);
GO

-- Creating primary key on [CODIGOIMPUESTOCOMPROBANTE] in table 'IMPUESTOCOMPROBANTE'
ALTER TABLE [dbo].[IMPUESTOCOMPROBANTE]
ADD CONSTRAINT [PK_IMPUESTOCOMPROBANTE]
    PRIMARY KEY CLUSTERED ([CODIGOIMPUESTOCOMPROBANTE] ASC);
GO

-- Creating primary key on [CODIGOLISTADEPRECIO] in table 'LISTADEPRECIO'
ALTER TABLE [dbo].[LISTADEPRECIO]
ADD CONSTRAINT [PK_LISTADEPRECIO]
    PRIMARY KEY CLUSTERED ([CODIGOLISTADEPRECIO] ASC);
GO

-- Creating primary key on [CODIGOPARAMETRO] in table 'PARAMETRO'
ALTER TABLE [dbo].[PARAMETRO]
ADD CONSTRAINT [PK_PARAMETRO]
    PRIMARY KEY CLUSTERED ([CODIGOPARAMETRO] ASC);
GO

-- Creating primary key on [CODIGO] in table 'PRODUCTO'
ALTER TABLE [dbo].[PRODUCTO]
ADD CONSTRAINT [PK_PRODUCTO]
    PRIMARY KEY CLUSTERED ([CODIGO] ASC);
GO

-- Creating primary key on [CODIGOPROVEEDOR] in table 'PROVEEDOR'
ALTER TABLE [dbo].[PROVEEDOR]
ADD CONSTRAINT [PK_PROVEEDOR]
    PRIMARY KEY CLUSTERED ([CODIGOPROVEEDOR] ASC);
GO

-- Creating primary key on [CODIGOPROVEEDORCERTIFICADO] in table 'PROVEEDORCERTIFICADO'
ALTER TABLE [dbo].[PROVEEDORCERTIFICADO]
ADD CONSTRAINT [PK_PROVEEDORCERTIFICADO]
    PRIMARY KEY CLUSTERED ([CODIGOPROVEEDORCERTIFICADO] ASC);
GO

-- Creating primary key on [CODIGOPUNTOEMISION] in table 'PUNTOEMISION'
ALTER TABLE [dbo].[PUNTOEMISION]
ADD CONSTRAINT [PK_PUNTOEMISION]
    PRIMARY KEY CLUSTERED ([CODIGOPUNTOEMISION] ASC);
GO

-- Creating primary key on [CODIGOPUNTOEMISIONAUTORIZACION] in table 'PUNTOEMISIONAUTORIZACION'
ALTER TABLE [dbo].[PUNTOEMISIONAUTORIZACION]
ADD CONSTRAINT [PK_PUNTOEMISIONAUTORIZACION]
    PRIMARY KEY CLUSTERED ([CODIGOPUNTOEMISIONAUTORIZACION] ASC);
GO

-- Creating primary key on [CODIGOPUNTOEMISIONDOCUMENTO] in table 'PUNTOEMISIONDOCUMENTO'
ALTER TABLE [dbo].[PUNTOEMISIONDOCUMENTO]
ADD CONSTRAINT [PK_PUNTOEMISIONDOCUMENTO]
    PRIMARY KEY CLUSTERED ([CODIGOPUNTOEMISIONDOCUMENTO] ASC);
GO

-- Creating primary key on [CODIGOSOCIONEGOCIO] in table 'SOCIONEGOCIO'
ALTER TABLE [dbo].[SOCIONEGOCIO]
ADD CONSTRAINT [PK_SOCIONEGOCIO]
    PRIMARY KEY CLUSTERED ([CODIGOSOCIONEGOCIO] ASC);
GO

-- Creating primary key on [Id] in table 'TABLAIMPUESTOS'
ALTER TABLE [dbo].[TABLAIMPUESTOS]
ADD CONSTRAINT [PK_TABLAIMPUESTOS]
    PRIMARY KEY CLUSTERED ([Id] ASC);
GO

-- Creating primary key on [CODIGOTIPOAMBIENTE] in table 'TIPOAMBIENTE'
ALTER TABLE [dbo].[TIPOAMBIENTE]
ADD CONSTRAINT [PK_TIPOAMBIENTE]
    PRIMARY KEY CLUSTERED ([CODIGOTIPOAMBIENTE] ASC);
GO

-- Creating primary key on [CODIGOTIPOARTICULO] in table 'TIPOARTICULO'
ALTER TABLE [dbo].[TIPOARTICULO]
ADD CONSTRAINT [PK_TIPOARTICULO]
    PRIMARY KEY CLUSTERED ([CODIGOTIPOARTICULO] ASC);
GO

-- Creating primary key on [CODIGOTIPOCOMPROBANTE] in table 'TIPOCOMPROBANTE'
ALTER TABLE [dbo].[TIPOCOMPROBANTE]
ADD CONSTRAINT [PK_TIPOCOMPROBANTE]
    PRIMARY KEY CLUSTERED ([CODIGOTIPOCOMPROBANTE] ASC);
GO

-- Creating primary key on [CODIGOTIPOELEMENTO] in table 'TIPOELEMENTO'
ALTER TABLE [dbo].[TIPOELEMENTO]
ADD CONSTRAINT [PK_TIPOELEMENTO]
    PRIMARY KEY CLUSTERED ([CODIGOTIPOELEMENTO] ASC);
GO

-- Creating primary key on [CODIGOTIPOESTADO] in table 'TIPOESTADO'
ALTER TABLE [dbo].[TIPOESTADO]
ADD CONSTRAINT [PK_TIPOESTADO]
    PRIMARY KEY CLUSTERED ([CODIGOTIPOESTADO] ASC);
GO

-- Creating primary key on [CODIGOTIPOFORMAPAGO] in table 'TIPOFORMAPAGO'
ALTER TABLE [dbo].[TIPOFORMAPAGO]
ADD CONSTRAINT [PK_TIPOFORMAPAGO]
    PRIMARY KEY CLUSTERED ([CODIGOTIPOFORMAPAGO] ASC);
GO

-- Creating primary key on [CODIGOTIPOIDENTIFICACION] in table 'TIPOIDENTIFICACION'
ALTER TABLE [dbo].[TIPOIDENTIFICACION]
ADD CONSTRAINT [PK_TIPOIDENTIFICACION]
    PRIMARY KEY CLUSTERED ([CODIGOTIPOIDENTIFICACION] ASC);
GO

-- Creating primary key on [CODIGOTIPOIMPUESTO] in table 'TIPOIMPUESTO'
ALTER TABLE [dbo].[TIPOIMPUESTO]
ADD CONSTRAINT [PK_TIPOIMPUESTO]
    PRIMARY KEY CLUSTERED ([CODIGOTIPOIMPUESTO] ASC);
GO

-- Creating primary key on [CODIGOUNIDAD] in table 'UNIDAD'
ALTER TABLE [dbo].[UNIDAD]
ADD CONSTRAINT [PK_UNIDAD]
    PRIMARY KEY CLUSTERED ([CODIGOUNIDAD] ASC);
GO

-- Creating primary key on [CODIGOUNIDADTIEMPO] in table 'UNIDADTIEMPO'
ALTER TABLE [dbo].[UNIDADTIEMPO]
ADD CONSTRAINT [PK_UNIDADTIEMPO]
    PRIMARY KEY CLUSTERED ([CODIGOUNIDADTIEMPO] ASC);
GO

-- Creating primary key on [CODIGOUSUARIO] in table 'USUARIO'
ALTER TABLE [dbo].[USUARIO]
ADD CONSTRAINT [PK_USUARIO]
    PRIMARY KEY CLUSTERED ([CODIGOUSUARIO] ASC);
GO

-- Creating primary key on [CODIGOUSUARIOEMPRESA] in table 'USUARIOEMPRESA'
ALTER TABLE [dbo].[USUARIOEMPRESA]
ADD CONSTRAINT [PK_USUARIOEMPRESA]
    PRIMARY KEY CLUSTERED ([CODIGOUSUARIOEMPRESA] ASC);
GO

-- Creating primary key on [CODIGOVENDEDOR] in table 'VENDEDOR'
ALTER TABLE [dbo].[VENDEDOR]
ADD CONSTRAINT [PK_VENDEDOR]
    PRIMARY KEY CLUSTERED ([CODIGOVENDEDOR] ASC);
GO

-- Creating primary key on [TIPOSOCIONEGOCIO], [CODIGOSOCIONEGOCIO], [CODIGO] in table 'V_SOCIONEGOCIO'
ALTER TABLE [dbo].[V_SOCIONEGOCIO]
ADD CONSTRAINT [PK_V_SOCIONEGOCIO]
    PRIMARY KEY CLUSTERED ([TIPOSOCIONEGOCIO], [CODIGOSOCIONEGOCIO], [CODIGO] ASC);
GO

-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on [CODIGOEMPRESA] in table 'ARTICULO'
ALTER TABLE [dbo].[ARTICULO]
ADD CONSTRAINT [FK_ARTICULO_EMPRESA]
    FOREIGN KEY ([CODIGOEMPRESA])
    REFERENCES [dbo].[EMPRESA]
        ([CODIGOEMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ARTICULO_EMPRESA'
CREATE INDEX [IX_FK_ARTICULO_EMPRESA]
ON [dbo].[ARTICULO]
    ([CODIGOEMPRESA]);
GO

-- Creating foreign key on [CODIGOIMPUESTO] in table 'ARTICULO'
ALTER TABLE [dbo].[ARTICULO]
ADD CONSTRAINT [FK_ARTICULO_IMPUESTO]
    FOREIGN KEY ([CODIGOIMPUESTO])
    REFERENCES [dbo].[IMPUESTO]
        ([CODIGOIMPUESTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ARTICULO_IMPUESTO'
CREATE INDEX [IX_FK_ARTICULO_IMPUESTO]
ON [dbo].[ARTICULO]
    ([CODIGOIMPUESTO]);
GO

-- Creating foreign key on [CODIGOTIPOARTICULO] in table 'ARTICULO'
ALTER TABLE [dbo].[ARTICULO]
ADD CONSTRAINT [FK_ARTICULO_TIPOARTICULO]
    FOREIGN KEY ([CODIGOTIPOARTICULO])
    REFERENCES [dbo].[TIPOARTICULO]
        ([CODIGOTIPOARTICULO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ARTICULO_TIPOARTICULO'
CREATE INDEX [IX_FK_ARTICULO_TIPOARTICULO]
ON [dbo].[ARTICULO]
    ([CODIGOTIPOARTICULO]);
GO

-- Creating foreign key on [CODIGOUNIDAD] in table 'ARTICULO'
ALTER TABLE [dbo].[ARTICULO]
ADD CONSTRAINT [FK_ARTICULO_UNIDAD]
    FOREIGN KEY ([CODIGOUNIDAD])
    REFERENCES [dbo].[UNIDAD]
        ([CODIGOUNIDAD])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ARTICULO_UNIDAD'
CREATE INDEX [IX_FK_ARTICULO_UNIDAD]
ON [dbo].[ARTICULO]
    ([CODIGOUNIDAD]);
GO

-- Creating foreign key on [CODIGOARTICULO] in table 'ARTICULOCOMPONENTE'
ALTER TABLE [dbo].[ARTICULOCOMPONENTE]
ADD CONSTRAINT [FK_ARTICULOCOMPONENTE_ARTICULO]
    FOREIGN KEY ([CODIGOARTICULO])
    REFERENCES [dbo].[ARTICULO]
        ([CODIGOARTICULO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ARTICULOCOMPONENTE_ARTICULO'
CREATE INDEX [IX_FK_ARTICULOCOMPONENTE_ARTICULO]
ON [dbo].[ARTICULOCOMPONENTE]
    ([CODIGOARTICULO]);
GO

-- Creating foreign key on [CODIGOARTICULOCOMP] in table 'ARTICULOCOMPONENTE'
ALTER TABLE [dbo].[ARTICULOCOMPONENTE]
ADD CONSTRAINT [FK_ARTICULOCOMPONENTE_ARTICULOCOMP]
    FOREIGN KEY ([CODIGOARTICULOCOMP])
    REFERENCES [dbo].[ARTICULO]
        ([CODIGOARTICULO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ARTICULOCOMPONENTE_ARTICULOCOMP'
CREATE INDEX [IX_FK_ARTICULOCOMPONENTE_ARTICULOCOMP]
ON [dbo].[ARTICULOCOMPONENTE]
    ([CODIGOARTICULOCOMP]);
GO

-- Creating foreign key on [CODIGOARTICULO] in table 'ARTICULOIMPUESTO'
ALTER TABLE [dbo].[ARTICULOIMPUESTO]
ADD CONSTRAINT [FK_ARTICULOIMPUESTO_ARTICULO]
    FOREIGN KEY ([CODIGOARTICULO])
    REFERENCES [dbo].[ARTICULO]
        ([CODIGOARTICULO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ARTICULOIMPUESTO_ARTICULO'
CREATE INDEX [IX_FK_ARTICULOIMPUESTO_ARTICULO]
ON [dbo].[ARTICULOIMPUESTO]
    ([CODIGOARTICULO]);
GO

-- Creating foreign key on [CODIGOARTICULO] in table 'BODEGASTOCK'
ALTER TABLE [dbo].[BODEGASTOCK]
ADD CONSTRAINT [FK_BODEGASTOCK_ARTICULO]
    FOREIGN KEY ([CODIGOARTICULO])
    REFERENCES [dbo].[ARTICULO]
        ([CODIGOARTICULO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_BODEGASTOCK_ARTICULO'
CREATE INDEX [IX_FK_BODEGASTOCK_ARTICULO]
ON [dbo].[BODEGASTOCK]
    ([CODIGOARTICULO]);
GO

-- Creating foreign key on [CODIGOARTICULO] in table 'DETALLECOMPROBANTE'
ALTER TABLE [dbo].[DETALLECOMPROBANTE]
ADD CONSTRAINT [FK_DETALLECOMPROBANTE_ARTICULO]
    FOREIGN KEY ([CODIGOARTICULO])
    REFERENCES [dbo].[ARTICULO]
        ([CODIGOARTICULO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_DETALLECOMPROBANTE_ARTICULO'
CREATE INDEX [IX_FK_DETALLECOMPROBANTE_ARTICULO]
ON [dbo].[DETALLECOMPROBANTE]
    ([CODIGOARTICULO]);
GO

-- Creating foreign key on [CODIGOARTICULO] in table 'DETALLELISTADEPRECIO'
ALTER TABLE [dbo].[DETALLELISTADEPRECIO]
ADD CONSTRAINT [FK_DETALLELISTADEPRECIOARTICULO]
    FOREIGN KEY ([CODIGOARTICULO])
    REFERENCES [dbo].[ARTICULO]
        ([CODIGOARTICULO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_DETALLELISTADEPRECIOARTICULO'
CREATE INDEX [IX_FK_DETALLELISTADEPRECIOARTICULO]
ON [dbo].[DETALLELISTADEPRECIO]
    ([CODIGOARTICULO]);
GO

-- Creating foreign key on [CODIGOUNIDAD] in table 'ARTICULOCOMPONENTE'
ALTER TABLE [dbo].[ARTICULOCOMPONENTE]
ADD CONSTRAINT [FK_ARTICULOCOMPONENTE_UNIDAD]
    FOREIGN KEY ([CODIGOUNIDAD])
    REFERENCES [dbo].[UNIDAD]
        ([CODIGOUNIDAD])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ARTICULOCOMPONENTE_UNIDAD'
CREATE INDEX [IX_FK_ARTICULOCOMPONENTE_UNIDAD]
ON [dbo].[ARTICULOCOMPONENTE]
    ([CODIGOUNIDAD]);
GO

-- Creating foreign key on [CODIGOIMPUESTO] in table 'ARTICULOIMPUESTO'
ALTER TABLE [dbo].[ARTICULOIMPUESTO]
ADD CONSTRAINT [FK_ARTICULOIMPUESTO_IMPUESTO]
    FOREIGN KEY ([CODIGOIMPUESTO])
    REFERENCES [dbo].[IMPUESTO]
        ([CODIGOIMPUESTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ARTICULOIMPUESTO_IMPUESTO'
CREATE INDEX [IX_FK_ARTICULOIMPUESTO_IMPUESTO]
ON [dbo].[ARTICULOIMPUESTO]
    ([CODIGOIMPUESTO]);
GO

-- Creating foreign key on [CODIGOEMPRESA] in table 'BODEGA'
ALTER TABLE [dbo].[BODEGA]
ADD CONSTRAINT [FK_BODEGA_EMPRESA]
    FOREIGN KEY ([CODIGOEMPRESA])
    REFERENCES [dbo].[EMPRESA]
        ([CODIGOEMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_BODEGA_EMPRESA'
CREATE INDEX [IX_FK_BODEGA_EMPRESA]
ON [dbo].[BODEGA]
    ([CODIGOEMPRESA]);
GO

-- Creating foreign key on [CODIGOESTABLECIMIENTO] in table 'BODEGA'
ALTER TABLE [dbo].[BODEGA]
ADD CONSTRAINT [FK_BODEGA_ESTABLECIMIENTO]
    FOREIGN KEY ([CODIGOESTABLECIMIENTO])
    REFERENCES [dbo].[ESTABLECIMIENTO]
        ([CODIGOESTABLECIMIENTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_BODEGA_ESTABLECIMIENTO'
CREATE INDEX [IX_FK_BODEGA_ESTABLECIMIENTO]
ON [dbo].[BODEGA]
    ([CODIGOESTABLECIMIENTO]);
GO

-- Creating foreign key on [CODIGOBODEGA] in table 'BODEGASTOCK'
ALTER TABLE [dbo].[BODEGASTOCK]
ADD CONSTRAINT [FK_BODEGASTOCK_BODEGA]
    FOREIGN KEY ([CODIGOBODEGA])
    REFERENCES [dbo].[BODEGA]
        ([CODIGOBODEGA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_BODEGASTOCK_BODEGA'
CREATE INDEX [IX_FK_BODEGASTOCK_BODEGA]
ON [dbo].[BODEGASTOCK]
    ([CODIGOBODEGA]);
GO

-- Creating foreign key on [CODIGOBODEGA] in table 'COMPROBANTE'
ALTER TABLE [dbo].[COMPROBANTE]
ADD CONSTRAINT [FK_COMPROBANTE_BODEGA]
    FOREIGN KEY ([CODIGOBODEGA])
    REFERENCES [dbo].[BODEGA]
        ([CODIGOBODEGA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_COMPROBANTE_BODEGA'
CREATE INDEX [IX_FK_COMPROBANTE_BODEGA]
ON [dbo].[COMPROBANTE]
    ([CODIGOBODEGA]);
GO

-- Creating foreign key on [CODIGOBODEGA] in table 'DETALLECOMPROBANTE'
ALTER TABLE [dbo].[DETALLECOMPROBANTE]
ADD CONSTRAINT [FK_DETALLECOMPROBANTE_BODEGA]
    FOREIGN KEY ([CODIGOBODEGA])
    REFERENCES [dbo].[BODEGA]
        ([CODIGOBODEGA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_DETALLECOMPROBANTE_BODEGA'
CREATE INDEX [IX_FK_DETALLECOMPROBANTE_BODEGA]
ON [dbo].[DETALLECOMPROBANTE]
    ([CODIGOBODEGA]);
GO

-- Creating foreign key on [CODIGOSOCIONEGOCIO] in table 'CLIENTE'
ALTER TABLE [dbo].[CLIENTE]
ADD CONSTRAINT [FK_CLIENTE_SOCIONEGOCIO]
    FOREIGN KEY ([CODIGOSOCIONEGOCIO])
    REFERENCES [dbo].[SOCIONEGOCIO]
        ([CODIGOSOCIONEGOCIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CLIENTE_SOCIONEGOCIO'
CREATE INDEX [IX_FK_CLIENTE_SOCIONEGOCIO]
ON [dbo].[CLIENTE]
    ([CODIGOSOCIONEGOCIO]);
GO

-- Creating foreign key on [CODIGOEMPRESA] in table 'CLIENTE'
ALTER TABLE [dbo].[CLIENTE]
ADD CONSTRAINT [FK_CODIGOEMPRESA]
    FOREIGN KEY ([CODIGOEMPRESA])
    REFERENCES [dbo].[EMPRESA]
        ([CODIGOEMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_CODIGOEMPRESA'
CREATE INDEX [IX_FK_CODIGOEMPRESA]
ON [dbo].[CLIENTE]
    ([CODIGOEMPRESA]);
GO

-- Creating foreign key on [CODIGOESTADOCOMPROBANTE] in table 'COMPROBANTE'
ALTER TABLE [dbo].[COMPROBANTE]
ADD CONSTRAINT [FK_COMPROBANTE_ESTADOCOMPROBANTE]
    FOREIGN KEY ([CODIGOESTADOCOMPROBANTE])
    REFERENCES [dbo].[ESTADOCOMPROBANTE]
        ([CODIGOESTADOCOMPROBANTE])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_COMPROBANTE_ESTADOCOMPROBANTE'
CREATE INDEX [IX_FK_COMPROBANTE_ESTADOCOMPROBANTE]
ON [dbo].[COMPROBANTE]
    ([CODIGOESTADOCOMPROBANTE]);
GO

-- Creating foreign key on [CODIGOCOMPROBANTE] in table 'COMPROBANTEFORMAPAGO'
ALTER TABLE [dbo].[COMPROBANTEFORMAPAGO]
ADD CONSTRAINT [FK_COMPROBANTEFORMAPAGO_COMPROBANTE]
    FOREIGN KEY ([CODIGOCOMPROBANTE])
    REFERENCES [dbo].[COMPROBANTE]
        ([CODIGOCOMPROBANTE])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_COMPROBANTEFORMAPAGO_COMPROBANTE'
CREATE INDEX [IX_FK_COMPROBANTEFORMAPAGO_COMPROBANTE]
ON [dbo].[COMPROBANTEFORMAPAGO]
    ([CODIGOCOMPROBANTE]);
GO

-- Creating foreign key on [CODIGOCOMPROBANTE] in table 'DETALLECOMPROBANTE'
ALTER TABLE [dbo].[DETALLECOMPROBANTE]
ADD CONSTRAINT [FK_DETALLECOMPROBANTE_COMPROBANTE]
    FOREIGN KEY ([CODIGOCOMPROBANTE])
    REFERENCES [dbo].[COMPROBANTE]
        ([CODIGOCOMPROBANTE])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_DETALLECOMPROBANTE_COMPROBANTE'
CREATE INDEX [IX_FK_DETALLECOMPROBANTE_COMPROBANTE]
ON [dbo].[DETALLECOMPROBANTE]
    ([CODIGOCOMPROBANTE]);
GO

-- Creating foreign key on [CODIGOEMPRESA] in table 'COMPROBANTE'
ALTER TABLE [dbo].[COMPROBANTE]
ADD CONSTRAINT [FK_EMPRESACOMPROBANTE]
    FOREIGN KEY ([CODIGOEMPRESA])
    REFERENCES [dbo].[EMPRESA]
        ([CODIGOEMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_EMPRESACOMPROBANTE'
CREATE INDEX [IX_FK_EMPRESACOMPROBANTE]
ON [dbo].[COMPROBANTE]
    ([CODIGOEMPRESA]);
GO

-- Creating foreign key on [CODIGOESTABLECIMIENTO] in table 'COMPROBANTE'
ALTER TABLE [dbo].[COMPROBANTE]
ADD CONSTRAINT [FK_ESTABLECIMIENTOCOMPROBANTE]
    FOREIGN KEY ([CODIGOESTABLECIMIENTO])
    REFERENCES [dbo].[ESTABLECIMIENTO]
        ([CODIGOESTABLECIMIENTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ESTABLECIMIENTOCOMPROBANTE'
CREATE INDEX [IX_FK_ESTABLECIMIENTOCOMPROBANTE]
ON [dbo].[COMPROBANTE]
    ([CODIGOESTABLECIMIENTO]);
GO

-- Creating foreign key on [CODIGOCOMPROBANTE] in table 'IMPUESTOCOMPROBANTE'
ALTER TABLE [dbo].[IMPUESTOCOMPROBANTE]
ADD CONSTRAINT [FK_IMPUESTOCOMPROBANTE_COMPROBANTE]
    FOREIGN KEY ([CODIGOCOMPROBANTE])
    REFERENCES [dbo].[COMPROBANTE]
        ([CODIGOCOMPROBANTE])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_IMPUESTOCOMPROBANTE_COMPROBANTE'
CREATE INDEX [IX_FK_IMPUESTOCOMPROBANTE_COMPROBANTE]
ON [dbo].[IMPUESTOCOMPROBANTE]
    ([CODIGOCOMPROBANTE]);
GO

-- Creating foreign key on [CODIGOPUNTOEMISION] in table 'COMPROBANTE'
ALTER TABLE [dbo].[COMPROBANTE]
ADD CONSTRAINT [FK_PUNTOEMISIONCOMPROBANTE]
    FOREIGN KEY ([CODIGOPUNTOEMISION])
    REFERENCES [dbo].[PUNTOEMISION]
        ([CODIGOPUNTOEMISION])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PUNTOEMISIONCOMPROBANTE'
CREATE INDEX [IX_FK_PUNTOEMISIONCOMPROBANTE]
ON [dbo].[COMPROBANTE]
    ([CODIGOPUNTOEMISION]);
GO

-- Creating foreign key on [CODIGOSOCIONEGOCIO] in table 'COMPROBANTE'
ALTER TABLE [dbo].[COMPROBANTE]
ADD CONSTRAINT [FK_SOCIONEGOCIOCOMPROBANTE]
    FOREIGN KEY ([CODIGOSOCIONEGOCIO])
    REFERENCES [dbo].[SOCIONEGOCIO]
        ([CODIGOSOCIONEGOCIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_SOCIONEGOCIOCOMPROBANTE'
CREATE INDEX [IX_FK_SOCIONEGOCIOCOMPROBANTE]
ON [dbo].[COMPROBANTE]
    ([CODIGOSOCIONEGOCIO]);
GO

-- Creating foreign key on [CODIGOTIPOCOMPROBANTE] in table 'COMPROBANTE'
ALTER TABLE [dbo].[COMPROBANTE]
ADD CONSTRAINT [FK_TIPOCOMPROBANTECOMPROBANTE]
    FOREIGN KEY ([CODIGOTIPOCOMPROBANTE])
    REFERENCES [dbo].[TIPOCOMPROBANTE]
        ([CODIGOTIPOCOMPROBANTE])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TIPOCOMPROBANTECOMPROBANTE'
CREATE INDEX [IX_FK_TIPOCOMPROBANTECOMPROBANTE]
ON [dbo].[COMPROBANTE]
    ([CODIGOTIPOCOMPROBANTE]);
GO

-- Creating foreign key on [CODIGOVENDEDOR] in table 'COMPROBANTE'
ALTER TABLE [dbo].[COMPROBANTE]
ADD CONSTRAINT [FK_VENDEDORCOMPROBANTE]
    FOREIGN KEY ([CODIGOVENDEDOR])
    REFERENCES [dbo].[SOCIONEGOCIO]
        ([CODIGOSOCIONEGOCIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_VENDEDORCOMPROBANTE'
CREATE INDEX [IX_FK_VENDEDORCOMPROBANTE]
ON [dbo].[COMPROBANTE]
    ([CODIGOVENDEDOR]);
GO

-- Creating foreign key on [CODIGOFORMAPAGO] in table 'COMPROBANTEFORMAPAGO'
ALTER TABLE [dbo].[COMPROBANTEFORMAPAGO]
ADD CONSTRAINT [FK_COMPROBANTEFORMAPAGO_FORMAPAGO]
    FOREIGN KEY ([CODIGOFORMAPAGO])
    REFERENCES [dbo].[FORMAPAGO]
        ([CODIGOFORMAPAGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_COMPROBANTEFORMAPAGO_FORMAPAGO'
CREATE INDEX [IX_FK_COMPROBANTEFORMAPAGO_FORMAPAGO]
ON [dbo].[COMPROBANTEFORMAPAGO]
    ([CODIGOFORMAPAGO]);
GO

-- Creating foreign key on [CODIGOUNIDADTIEMPO] in table 'COMPROBANTEFORMAPAGO'
ALTER TABLE [dbo].[COMPROBANTEFORMAPAGO]
ADD CONSTRAINT [FK_COMPROBANTEFORMAPAGO_UNIDADTIEMPO]
    FOREIGN KEY ([CODIGOUNIDADTIEMPO])
    REFERENCES [dbo].[UNIDADTIEMPO]
        ([CODIGOUNIDADTIEMPO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_COMPROBANTEFORMAPAGO_UNIDADTIEMPO'
CREATE INDEX [IX_FK_COMPROBANTEFORMAPAGO_UNIDADTIEMPO]
ON [dbo].[COMPROBANTEFORMAPAGO]
    ([CODIGOUNIDADTIEMPO]);
GO

-- Creating foreign key on [CODIGOIMPUESTO] in table 'DETALLECOMPROBANTE'
ALTER TABLE [dbo].[DETALLECOMPROBANTE]
ADD CONSTRAINT [FK_DETALLECOMPROBANTE_IMPUESTO]
    FOREIGN KEY ([CODIGOIMPUESTO])
    REFERENCES [dbo].[IMPUESTO]
        ([CODIGOIMPUESTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_DETALLECOMPROBANTE_IMPUESTO'
CREATE INDEX [IX_FK_DETALLECOMPROBANTE_IMPUESTO]
ON [dbo].[DETALLECOMPROBANTE]
    ([CODIGOIMPUESTO]);
GO

-- Creating foreign key on [CODIGOLISTADEPRECIO] in table 'DETALLELISTADEPRECIO'
ALTER TABLE [dbo].[DETALLELISTADEPRECIO]
ADD CONSTRAINT [FK_DETALLELISTADEPRECIO]
    FOREIGN KEY ([CODIGOLISTADEPRECIO])
    REFERENCES [dbo].[LISTADEPRECIO]
        ([CODIGOLISTADEPRECIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_DETALLELISTADEPRECIO'
CREATE INDEX [IX_FK_DETALLELISTADEPRECIO]
ON [dbo].[DETALLELISTADEPRECIO]
    ([CODIGOLISTADEPRECIO]);
GO

-- Creating foreign key on [CODIGOTIPOELEMENTO] in table 'ELEMENTO'
ALTER TABLE [dbo].[ELEMENTO]
ADD CONSTRAINT [FK_TIPO_ELEMENTO]
    FOREIGN KEY ([CODIGOTIPOELEMENTO])
    REFERENCES [dbo].[TIPOELEMENTO]
        ([CODIGOTIPOELEMENTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_TIPO_ELEMENTO'
CREATE INDEX [IX_FK_TIPO_ELEMENTO]
ON [dbo].[ELEMENTO]
    ([CODIGOTIPOELEMENTO]);
GO

-- Creating foreign key on [CODIGOEMPRESA] in table 'UNIDAD'
ALTER TABLE [dbo].[UNIDAD]
ADD CONSTRAINT [FK_EMPRESA]
    FOREIGN KEY ([CODIGOEMPRESA])
    REFERENCES [dbo].[EMPRESA]
        ([CODIGOEMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_EMPRESA'
CREATE INDEX [IX_FK_EMPRESA]
ON [dbo].[UNIDAD]
    ([CODIGOEMPRESA]);
GO

-- Creating foreign key on [CODIGOPROVEEDORCERTIFICADO] in table 'EMPRESA'
ALTER TABLE [dbo].[EMPRESA]
ADD CONSTRAINT [FK_EMPRESA_PROVEEDORCERTIFICADO]
    FOREIGN KEY ([CODIGOPROVEEDORCERTIFICADO])
    REFERENCES [dbo].[PROVEEDORCERTIFICADO]
        ([CODIGOPROVEEDORCERTIFICADO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_EMPRESA_PROVEEDORCERTIFICADO'
CREATE INDEX [IX_FK_EMPRESA_PROVEEDORCERTIFICADO]
ON [dbo].[EMPRESA]
    ([CODIGOPROVEEDORCERTIFICADO]);
GO

-- Creating foreign key on [CODIGOTIPOAMBIENTE] in table 'EMPRESA'
ALTER TABLE [dbo].[EMPRESA]
ADD CONSTRAINT [FK_EMPRESA_TIPOAMBIENTE]
    FOREIGN KEY ([CODIGOTIPOAMBIENTE])
    REFERENCES [dbo].[TIPOAMBIENTE]
        ([CODIGOTIPOAMBIENTE])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_EMPRESA_TIPOAMBIENTE'
CREATE INDEX [IX_FK_EMPRESA_TIPOAMBIENTE]
ON [dbo].[EMPRESA]
    ([CODIGOTIPOAMBIENTE]);
GO

-- Creating foreign key on [CODIGOEMPRESA] in table 'ESTABLECIMIENTO'
ALTER TABLE [dbo].[ESTABLECIMIENTO]
ADD CONSTRAINT [FK_ESTABLECIMIENTO_ToTable]
    FOREIGN KEY ([CODIGOEMPRESA])
    REFERENCES [dbo].[EMPRESA]
        ([CODIGOEMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ESTABLECIMIENTO_ToTable'
CREATE INDEX [IX_FK_ESTABLECIMIENTO_ToTable]
ON [dbo].[ESTABLECIMIENTO]
    ([CODIGOEMPRESA]);
GO

-- Creating foreign key on [CODIGOEMPRESA] in table 'FORMAPAGO'
ALTER TABLE [dbo].[FORMAPAGO]
ADD CONSTRAINT [FK_FORMAPAGO_EMPRESA]
    FOREIGN KEY ([CODIGOEMPRESA])
    REFERENCES [dbo].[EMPRESA]
        ([CODIGOEMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_FORMAPAGO_EMPRESA'
CREATE INDEX [IX_FK_FORMAPAGO_EMPRESA]
ON [dbo].[FORMAPAGO]
    ([CODIGOEMPRESA]);
GO

-- Creating foreign key on [CODIGOEMPRESA] in table 'IMPUESTO'
ALTER TABLE [dbo].[IMPUESTO]
ADD CONSTRAINT [FK_IMPUESTO_EMPRESA]
    FOREIGN KEY ([CODIGOEMPRESA])
    REFERENCES [dbo].[EMPRESA]
        ([CODIGOEMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_IMPUESTO_EMPRESA'
CREATE INDEX [IX_FK_IMPUESTO_EMPRESA]
ON [dbo].[IMPUESTO]
    ([CODIGOEMPRESA]);
GO

-- Creating foreign key on [CODIGOEMPRESA] in table 'LISTADEPRECIO'
ALTER TABLE [dbo].[LISTADEPRECIO]
ADD CONSTRAINT [FK_LISTADEPRECIO_EMPRESA]
    FOREIGN KEY ([CODIGOEMPRESA])
    REFERENCES [dbo].[EMPRESA]
        ([CODIGOEMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_LISTADEPRECIO_EMPRESA'
CREATE INDEX [IX_FK_LISTADEPRECIO_EMPRESA]
ON [dbo].[LISTADEPRECIO]
    ([CODIGOEMPRESA]);
GO

-- Creating foreign key on [CODIGOEMPRESA] in table 'PARAMETRO'
ALTER TABLE [dbo].[PARAMETRO]
ADD CONSTRAINT [FK_PARAMETROS_EMPRESA]
    FOREIGN KEY ([CODIGOEMPRESA])
    REFERENCES [dbo].[EMPRESA]
        ([CODIGOEMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PARAMETROS_EMPRESA'
CREATE INDEX [IX_FK_PARAMETROS_EMPRESA]
ON [dbo].[PARAMETRO]
    ([CODIGOEMPRESA]);
GO

-- Creating foreign key on [CODIGOEMPRESA] in table 'PROVEEDOR'
ALTER TABLE [dbo].[PROVEEDOR]
ADD CONSTRAINT [FK_PROVEEDOREMPRESA]
    FOREIGN KEY ([CODIGOEMPRESA])
    REFERENCES [dbo].[EMPRESA]
        ([CODIGOEMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PROVEEDOREMPRESA'
CREATE INDEX [IX_FK_PROVEEDOREMPRESA]
ON [dbo].[PROVEEDOR]
    ([CODIGOEMPRESA]);
GO

-- Creating foreign key on [CODIGOEMPRESA] in table 'USUARIOEMPRESA'
ALTER TABLE [dbo].[USUARIOEMPRESA]
ADD CONSTRAINT [FK_USUARIOEMPRESA_EMPRESA]
    FOREIGN KEY ([CODIGOEMPRESA])
    REFERENCES [dbo].[EMPRESA]
        ([CODIGOEMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_USUARIOEMPRESA_EMPRESA'
CREATE INDEX [IX_FK_USUARIOEMPRESA_EMPRESA]
ON [dbo].[USUARIOEMPRESA]
    ([CODIGOEMPRESA]);
GO

-- Creating foreign key on [CODIGOEMPRESA] in table 'VENDEDOR'
ALTER TABLE [dbo].[VENDEDOR]
ADD CONSTRAINT [FK_VENDOREMPRESA]
    FOREIGN KEY ([CODIGOEMPRESA])
    REFERENCES [dbo].[EMPRESA]
        ([CODIGOEMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_VENDOREMPRESA'
CREATE INDEX [IX_FK_VENDOREMPRESA]
ON [dbo].[VENDEDOR]
    ([CODIGOEMPRESA]);
GO

-- Creating foreign key on [CODIGOESTABLECIMIENTO] in table 'PUNTOEMISION'
ALTER TABLE [dbo].[PUNTOEMISION]
ADD CONSTRAINT [FK_PUNTOEMISIONESTABLECIMIENTO]
    FOREIGN KEY ([CODIGOESTABLECIMIENTO])
    REFERENCES [dbo].[ESTABLECIMIENTO]
        ([CODIGOESTABLECIMIENTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PUNTOEMISIONESTABLECIMIENTO'
CREATE INDEX [IX_FK_PUNTOEMISIONESTABLECIMIENTO]
ON [dbo].[PUNTOEMISION]
    ([CODIGOESTABLECIMIENTO]);
GO

-- Creating foreign key on [CODIGOTIPOESTADO] in table 'ESTADOCOMPROBANTE'
ALTER TABLE [dbo].[ESTADOCOMPROBANTE]
ADD CONSTRAINT [FK_ESTADOCOMPROBANTE_TIPOESTADO]
    FOREIGN KEY ([CODIGOTIPOESTADO])
    REFERENCES [dbo].[TIPOESTADO]
        ([CODIGOTIPOESTADO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ESTADOCOMPROBANTE_TIPOESTADO'
CREATE INDEX [IX_FK_ESTADOCOMPROBANTE_TIPOESTADO]
ON [dbo].[ESTADOCOMPROBANTE]
    ([CODIGOTIPOESTADO]);
GO

-- Creating foreign key on [CODIGOTIPOFORMAPAGO] in table 'FORMAPAGO'
ALTER TABLE [dbo].[FORMAPAGO]
ADD CONSTRAINT [FK_FORMAPAGO_TIPOFORMAPAGO]
    FOREIGN KEY ([CODIGOTIPOFORMAPAGO])
    REFERENCES [dbo].[TIPOFORMAPAGO]
        ([CODIGOTIPOFORMAPAGO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_FORMAPAGO_TIPOFORMAPAGO'
CREATE INDEX [IX_FK_FORMAPAGO_TIPOFORMAPAGO]
ON [dbo].[FORMAPAGO]
    ([CODIGOTIPOFORMAPAGO]);
GO

-- Creating foreign key on [CODIGOTIPOIMPUESTO] in table 'IMPUESTO'
ALTER TABLE [dbo].[IMPUESTO]
ADD CONSTRAINT [FK_IMPUESTO_TIPOIMPUESTO]
    FOREIGN KEY ([CODIGOTIPOIMPUESTO])
    REFERENCES [dbo].[TIPOIMPUESTO]
        ([CODIGOTIPOIMPUESTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_IMPUESTO_TIPOIMPUESTO'
CREATE INDEX [IX_FK_IMPUESTO_TIPOIMPUESTO]
ON [dbo].[IMPUESTO]
    ([CODIGOTIPOIMPUESTO]);
GO

-- Creating foreign key on [CODIGOIMPUESTO] in table 'IMPUESTOCOMPROBANTE'
ALTER TABLE [dbo].[IMPUESTOCOMPROBANTE]
ADD CONSTRAINT [FK_IMPUESTOCOMPROBANTE_IMPUESTO]
    FOREIGN KEY ([CODIGOIMPUESTO])
    REFERENCES [dbo].[IMPUESTO]
        ([CODIGOIMPUESTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_IMPUESTOCOMPROBANTE_IMPUESTO'
CREATE INDEX [IX_FK_IMPUESTOCOMPROBANTE_IMPUESTO]
ON [dbo].[IMPUESTOCOMPROBANTE]
    ([CODIGOIMPUESTO]);
GO

-- Creating foreign key on [CODIGOSOCIONEGOCIO] in table 'LISTADEPRECIO'
ALTER TABLE [dbo].[LISTADEPRECIO]
ADD CONSTRAINT [FK_LISTADEPRECIO_SOCIONEGOCIO]
    FOREIGN KEY ([CODIGOSOCIONEGOCIO])
    REFERENCES [dbo].[SOCIONEGOCIO]
        ([CODIGOSOCIONEGOCIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_LISTADEPRECIO_SOCIONEGOCIO'
CREATE INDEX [IX_FK_LISTADEPRECIO_SOCIONEGOCIO]
ON [dbo].[LISTADEPRECIO]
    ([CODIGOSOCIONEGOCIO]);
GO

-- Creating foreign key on [CODIGOPUNTOEMISION] in table 'PUNTOEMISIONDOCUMENTO'
ALTER TABLE [dbo].[PUNTOEMISIONDOCUMENTO]
ADD CONSTRAINT [FK_PUNTOEMISIONDOCUMENTO_PUNTOEMISION]
    FOREIGN KEY ([CODIGOPUNTOEMISION])
    REFERENCES [dbo].[PUNTOEMISION]
        ([CODIGOPUNTOEMISION])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PUNTOEMISIONDOCUMENTO_PUNTOEMISION'
CREATE INDEX [IX_FK_PUNTOEMISIONDOCUMENTO_PUNTOEMISION]
ON [dbo].[PUNTOEMISIONDOCUMENTO]
    ([CODIGOPUNTOEMISION]);
GO

-- Creating foreign key on [CODIGOPUNTOEMISIONDOCUMENTO] in table 'PUNTOEMISIONAUTORIZACION'
ALTER TABLE [dbo].[PUNTOEMISIONAUTORIZACION]
ADD CONSTRAINT [FK_PUNTOEMISIONAUTORIZACION_ToTable]
    FOREIGN KEY ([CODIGOPUNTOEMISIONDOCUMENTO])
    REFERENCES [dbo].[PUNTOEMISIONDOCUMENTO]
        ([CODIGOPUNTOEMISIONDOCUMENTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PUNTOEMISIONAUTORIZACION_ToTable'
CREATE INDEX [IX_FK_PUNTOEMISIONAUTORIZACION_ToTable]
ON [dbo].[PUNTOEMISIONAUTORIZACION]
    ([CODIGOPUNTOEMISIONDOCUMENTO]);
GO

-- Creating foreign key on [CODIGOTIPOCOMPROBANTE] in table 'PUNTOEMISIONDOCUMENTO'
ALTER TABLE [dbo].[PUNTOEMISIONDOCUMENTO]
ADD CONSTRAINT [FK_PUNTOEMISIONDOCUMENTOTIPOCOMPROBANTE]
    FOREIGN KEY ([CODIGOTIPOCOMPROBANTE])
    REFERENCES [dbo].[TIPOCOMPROBANTE]
        ([CODIGOTIPOCOMPROBANTE])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PUNTOEMISIONDOCUMENTOTIPOCOMPROBANTE'
CREATE INDEX [IX_FK_PUNTOEMISIONDOCUMENTOTIPOCOMPROBANTE]
ON [dbo].[PUNTOEMISIONDOCUMENTO]
    ([CODIGOTIPOCOMPROBANTE]);
GO

-- Creating foreign key on [CODIGOTIPOIDENTIFICACION] in table 'SOCIONEGOCIO'
ALTER TABLE [dbo].[SOCIONEGOCIO]
ADD CONSTRAINT [FK_SOCIONEGOCIO_TIPOIDENTIFICACION]
    FOREIGN KEY ([CODIGOTIPOIDENTIFICACION])
    REFERENCES [dbo].[TIPOIDENTIFICACION]
        ([CODIGOTIPOIDENTIFICACION])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_SOCIONEGOCIO_TIPOIDENTIFICACION'
CREATE INDEX [IX_FK_SOCIONEGOCIO_TIPOIDENTIFICACION]
ON [dbo].[SOCIONEGOCIO]
    ([CODIGOTIPOIDENTIFICACION]);
GO

-- Creating foreign key on [CODIGOUSUARIO] in table 'USUARIOEMPRESA'
ALTER TABLE [dbo].[USUARIOEMPRESA]
ADD CONSTRAINT [FK_USUARIOEMPRESA_USUARIO]
    FOREIGN KEY ([CODIGOUSUARIO])
    REFERENCES [dbo].[USUARIO]
        ([CODIGOUSUARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_USUARIOEMPRESA_USUARIO'
CREATE INDEX [IX_FK_USUARIOEMPRESA_USUARIO]
ON [dbo].[USUARIOEMPRESA]
    ([CODIGOUSUARIO]);
GO

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------