//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nasti.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public int CODIGO { get; set; }
        public string CODIGO_PRINCIPAL { get; set; }
        public string CODIGO_AUXILIAR { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> VALOR_UNITARIO { get; set; }
        public string TIPO_PRODUCTO { get; set; }
        public string IVA { get; set; }
        public string ICE { get; set; }
        public string IRBPNR { get; set; }
    }
}
