//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nasti.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUNTOEMISIONDOCUMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PUNTOEMISIONDOCUMENTO()
        {
            this.PUNTOEMISIONAUTORIZACION = new HashSet<PUNTOEMISIONAUTORIZACION>();
        }
    
        public long CODIGOPUNTOEMISIONDOCUMENTO { get; set; }
        public Nullable<long> CODIGOPUNTOEMISION { get; set; }
        public Nullable<long> CODIGOTIPOCOMPROBANTE { get; set; }
        public Nullable<long> NUMERODOCUMENTO { get; set; }
        public Nullable<long> NUMEROPENDIENTE { get; set; }
        public byte[] ARCHIVOREPORTE { get; set; }
    
        public virtual PUNTOEMISION PUNTOEMISION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUNTOEMISIONAUTORIZACION> PUNTOEMISIONAUTORIZACION { get; set; }
        public virtual TIPOCOMPROBANTE TIPOCOMPROBANTE { get; set; }
    }
}
