//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nasti.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SOCIONEGOCIO
    {
        public int TIPOSOCIONEGOCIO { get; set; }
        public long CODIGOSOCIONEGOCIO { get; set; }
        public string RAZONSOCIAL { get; set; }
        public string NUMERODOCUMENTO { get; set; }
        public Nullable<long> CODIGOEMPRESA { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public string COMENTARIO { get; set; }
        public string NOMBRECOMERCIAL { get; set; }
        public Nullable<long> CODIGOTIPOIDENTIFICACION { get; set; }
        public long CODIGO { get; set; }
        public string ESTATUS { get; set; }
    }
}
